Route117School_MapScripts::
	.byte 0


Route117School_Text_Teacher::
	msgbox Route117School_Text_Teacher_Text_0, MSGBOX_NPC
	end


Route117School_Text_SchoolKidF::
	msgbox Route117School_Text_SchoolKidF_Text_0, MSGBOX_NPC
	end


Route117School_Text_SchoolKidM::
	msgbox Route117School_Text_SchoolKidM_Text_0, MSGBOX_NPC
	end


Route117School_Text_Lass::
	msgbox Route117School_Text_Lass_Text_0, MSGBOX_NPC
	end


Route117School_Text_Blackboard::
	msgbox Route117School_Text_Blackboard_Text_0, MSGBOX_SIGN
	end


Route117School_Text_Teacher_Text_0:
	.string "This SCHOOL is situated between\nMAUVILLE and VERDANTRUF because the\lauthorities couldn't decide which city\lwas the best suited for it.\lAnd there is the Day Care just close,\lso we specialize with BREEDING.$"

Route117School_Text_SchoolKidF_Text_0:
	.string "If a baby Pokémon’s parents know\ncertain moves, the baby might be born\lknowing them too!\lImagine a PICHU knowing God Tiers\lMOVES!\lAwesome!$"

Route117School_Text_SchoolKidM_Text_0:
	.string "Giving nicknames builds bonds with\nyour POKéMON... or at least, it feels\lthat way!\lI named my ZIGZAGOON “BAZOONGA”. It's\lcool right?\l{PLAYER}: No one asked you...$"

Route117School_Text_Lass_Text_0:
	.string "Usually, the baby POKéMON’s species\nmatches the mother. Except if there is\la DITTO involve.\lDon't ask how I know that.$"

Route117School_Text_Blackboard_Text_0:
	.string "{PLAYER}: It's the blackboard....\nHmmmm....\lIt's written two POKéMON need to be in\lthe same Egg Group to breed. You can’t\lbreed a Pikachu with a Tentacool.\lI should keep that in mind before\ltrying some, hmmm, experimentations...$"
