Underwater_Route131_MapScripts::
	.byte 0


AlphRuinsCave_Text_Scientist::
	msgbox AlphRuinsCave_Text_Scientist_Text_0, MSGBOX_NPC
	applymovement 2, AlphRuinsCave_Move_Scientist
	end


AlphRuinsCave_Move_Scientist:
	face_original_direction
	step_end

AlphRuinsCave_Text_Hiker::
	msgbox AlphRuinsCave_Text_Hiker_Text_0, MSGBOX_NPC
	end


AlphRuinsCave_Text_Gambler::
	msgbox AlphRuinsCave_Text_Gambler_Text_0, MSGBOX_NPC
	end


AlphRuinsCave_Text_Youngster::
	msgbox AlphRuinsCave_Text_Youngster_Text_0, MSGBOX_NPC
	end


AlphRuinsCave_Text_Channeler::
	msgbox AlphRuinsCave_Text_Channeler_Text_0, MSGBOX_NPC
	end


AlphRuins_Text_Panel::
	msgbox AlphRuins_Text_Panel_Text_0, MSGBOX_NPC
	end


AlphRuins_Text_A_Statue::
	msgbox AlphRuins_Text_A_Statue_Text_0, MSGBOX_NPC
	setwildbattle SPECIES_UNOWN, 25
	dowildbattle
	end


AlphRuins_Text_B_Statue::
	msgbox AlphRuins_Text_B_Statue_Text_0, MSGBOX_NPC
	setwildbattle SPECIES_UNOWN, 25
	dowildbattle
	end


AlphRuins_Text_C_Statue::
	msgbox AlphRuins_Text_C_Statue_Text_0, MSGBOX_NPC
	setwildbattle SPECIES_UNOWN, 25
	dowildbattle
	end


AlphRuins_Text_D_Statue::
	msgbox AlphRuins_Text_D_Statue_Text_0, MSGBOX_NPC
	setwildbattle SPECIES_UNOWN, 25
	dowildbattle
	end


AlphRuins_Text_E_Statue::
	msgbox AlphRuins_Text_E_Statue_Text_0, MSGBOX_NPC
	setwildbattle SPECIES_UNOWN, 25
	dowildbattle
	end


AlphRuins_Text_F_Statue::
	msgbox AlphRuins_Text_F_Statue_Text_0, MSGBOX_NPC
	setwildbattle SPECIES_UNOWN, 25
	dowildbattle
	end


AlphRuins_Text_G_Statue::
	msgbox AlphRuins_Text_G_Statue_Text_0, MSGBOX_NPC
	setwildbattle SPECIES_UNOWN, 25
	dowildbattle
	end


AlphRuins_Text_H_Statue::
	msgbox AlphRuins_Text_H_Statue_Text_0, MSGBOX_NPC
	setwildbattle SPECIES_UNOWN, 25
	dowildbattle
	end


AlphRuins_Text_I_Statue::
	msgbox AlphRuins_Text_I_Statue_Text_0, MSGBOX_NPC
	setwildbattle SPECIES_UNOWN, 25
	dowildbattle
	end


AlphRuins_Text_J_Statue::
	msgbox AlphRuins_Text_J_Statue_Text_0, MSGBOX_NPC
	setwildbattle SPECIES_UNOWN, 25
	dowildbattle
	end


AlphRuins_Text_K_Statue::
	msgbox AlphRuins_Text_K_Statue_Text_0, MSGBOX_NPC
	setwildbattle SPECIES_UNOWN, 25
	dowildbattle
	end


AlphRuins_Text_L_Statue::
	msgbox AlphRuins_Text_L_Statue_Text_0, MSGBOX_NPC
	setwildbattle SPECIES_UNOWN, 25
	dowildbattle
	end


AlphRuins_Text_M_Statue::
	msgbox AlphRuins_Text_M_Statue_Text_0, MSGBOX_NPC
	setwildbattle SPECIES_UNOWN, 25
	dowildbattle
	end


AlphRuins_Text_N_Statue::
	msgbox AlphRuins_Text_N_Statue_Text_0, MSGBOX_NPC
	setwildbattle SPECIES_UNOWN, 25
	dowildbattle
	end


AlphRuins_Text_O_Statue::
	msgbox AlphRuins_Text_O_Statue_Text_0, MSGBOX_NPC
	setwildbattle SPECIES_UNOWN, 25
	dowildbattle
	end


AlphRuins_Text_P_Statue::
	msgbox AlphRuins_Text_P_Statue_Text_0, MSGBOX_NPC
	setwildbattle SPECIES_UNOWN, 25
	dowildbattle
	end


AlphRuins_Text_Q_Statue::
	msgbox AlphRuins_Text_Q_Statue_Text_0, MSGBOX_NPC
	setwildbattle SPECIES_UNOWN, 25
	dowildbattle
	end


AlphRuins_Text_R_Statue::
	msgbox AlphRuins_Text_R_Statue_Text_0, MSGBOX_NPC
	setwildbattle SPECIES_UNOWN, 25
	dowildbattle
	end


AlphRuins_Text_S_Statue::
	msgbox AlphRuins_Text_S_Statue_Text_0, MSGBOX_NPC
	setwildbattle SPECIES_UNOWN, 25
	dowildbattle
	end


AlphRuins_Text_T_Statue::
	msgbox AlphRuins_Text_T_Statue_Text_0, MSGBOX_NPC
	setwildbattle SPECIES_UNOWN, 25
	dowildbattle
	end


AlphRuins_Text_U_Statue::
	msgbox AlphRuins_Text_U_Statue_Text_0, MSGBOX_NPC
	setwildbattle SPECIES_UNOWN, 25
	dowildbattle
	end


AlphRuins_Text_V_Statue::
	msgbox AlphRuins_Text_V_Statue_Text_0, MSGBOX_NPC
	setwildbattle SPECIES_UNOWN, 25
	dowildbattle
	end


AlphRuins_Text_W_Statue::
	msgbox AlphRuins_Text_W_Statue_Text_0, MSGBOX_NPC
	setwildbattle SPECIES_UNOWN, 25
	dowildbattle
	end


AlphRuins_Text_X_Statue::
	msgbox AlphRuins_Text_X_Statue_Text_0, MSGBOX_NPC
	setwildbattle SPECIES_UNOWN, 25
	dowildbattle
	end


AlphRuins_Text_Y_Statue::
	msgbox AlphRuins_Text_Y_Statue_Text_0, MSGBOX_NPC
	setwildbattle SPECIES_UNOWN, 25
	dowildbattle
	end


AlphRuins_Text_Z_Statue::
	msgbox AlphRuins_Text_Z_Statue_Text_0, MSGBOX_NPC
	setwildbattle SPECIES_UNOWN, 25
	dowildbattle
	end


AlphRuins_Text_Question_Statue::
	msgbox AlphRuins_Text_Question_Statue_Text_0, MSGBOX_NPC
	setwildbattle SPECIES_UNOWN, 25
	dowildbattle
	end


AlphRuins_Text_Exclamation_Statue::
	msgbox AlphRuins_Text_Exclamation_Statue_Text_0, MSGBOX_NPC
	setwildbattle SPECIES_UNOWN, 25
	dowildbattle
	end


AlphRuinsCave_Text_Scientist_Text_0:
	.string "This panel makes no sense!\nWhat do you mean it's a child play?!\lI have a PHD!$"

AlphRuinsCave_Text_Hiker_Text_0:
	.string "Scientist called the HIKER CLUB in case\nof landsliding.\lSo far nothing is happening, and I\ldon't think that anything will happen\lsoon.$"

AlphRuinsCave_Text_Gambler_Text_0:
	.string "The atmosphere here...\nIt reminds me of the worst place I've\lbeen to:\lThe foul smell, the sensation of being\lwatch, the feeling of being surrounded\lby undead...\l.......................................\lYes! That's exactly a retirement home!$"

AlphRuinsCave_Text_Youngster_Text_0:
	.string "I think there are ghost around here...$"

AlphRuinsCave_Text_Channeler_Text_0:
	.string "The statues... It's like it looking at\nme...\lMay ARCEUS bless my soul.$"

AlphRuins_Text_Panel_Text_0:
	.string "{PLAYER}: Hmmm...\nIt's an old panel. Looks like a\lpuzzle...\lHow old am I to do stuff like that\lseriously?$"

AlphRuins_Text_A_Statue_Text_0:
	.string "{PLAYER}: It looks like a... A?\nWhat's that?$"

AlphRuins_Text_B_Statue_Text_0:
	.string "{PLAYER}: It looks like a... B?\nWhat's that?$"

AlphRuins_Text_C_Statue_Text_0:
	.string "{PLAYER}: It looks like a... C?\nWhat's that?$"

AlphRuins_Text_D_Statue_Text_0:
	.string "{PLAYER}: It looks like a... D?\nWhat's that?$"

AlphRuins_Text_E_Statue_Text_0:
	.string "{PLAYER}: It looks like a... E?\nWhat's that?$"

AlphRuins_Text_F_Statue_Text_0:
	.string "{PLAYER}: It looks like a... F?\nWhat's that?$"

AlphRuins_Text_G_Statue_Text_0:
	.string "{PLAYER}: It looks like a... G?\nWhat's that?$"

AlphRuins_Text_H_Statue_Text_0:
	.string "{PLAYER}: It looks like a... H?\nWhat's that?$"

AlphRuins_Text_I_Statue_Text_0:
	.string "{PLAYER}: It looks like a... I?\nWhat's that?$"

AlphRuins_Text_J_Statue_Text_0:
	.string "{PLAYER}: It looks like a... J?\nWhat's that?$"

AlphRuins_Text_K_Statue_Text_0:
	.string "{PLAYER}: It looks like a... K?\nWhat's that?$"

AlphRuins_Text_L_Statue_Text_0:
	.string "{PLAYER}: It looks like a... L?\nWhat's that?$"

AlphRuins_Text_M_Statue_Text_0:
	.string "{PLAYER}: It looks like a... M?\nWhat's that?$"

AlphRuins_Text_N_Statue_Text_0:
	.string "{PLAYER}: It looks like a... N?\nWhat's that?$"

AlphRuins_Text_O_Statue_Text_0:
	.string "{PLAYER}: It looks like a... O?\nWhat's that?$"

AlphRuins_Text_P_Statue_Text_0:
	.string "{PLAYER}: It looks like a... P?\nWhat's that?$"

AlphRuins_Text_Q_Statue_Text_0:
	.string "{PLAYER}: It looks like a... Q?\nWhat's that?$"

AlphRuins_Text_R_Statue_Text_0:
	.string "{PLAYER}: It looks like a... R?\nWhat's that?$"

AlphRuins_Text_S_Statue_Text_0:
	.string "{PLAYER}: It looks like a... S?\nWhat's that?$"

AlphRuins_Text_T_Statue_Text_0:
	.string "{PLAYER}: It looks like a... T?\nWhat's that?$"

AlphRuins_Text_U_Statue_Text_0:
	.string "{PLAYER}: It looks like a... U?\nWhat's that?$"

AlphRuins_Text_V_Statue_Text_0:
	.string "{PLAYER}: It looks like a... V?\nWhat's that?$"

AlphRuins_Text_W_Statue_Text_0:
	.string "{PLAYER}: It looks like a... W?\nWhat's that?$"

AlphRuins_Text_X_Statue_Text_0:
	.string "{PLAYER}: It looks like a... X?\nWhat's that?$"

AlphRuins_Text_Y_Statue_Text_0:
	.string "{PLAYER}: It looks like a... Y?\nWhat's that?$"

AlphRuins_Text_Z_Statue_Text_0:
	.string "{PLAYER}: It looks like a... Z?\nWhat's that?$"

AlphRuins_Text_Question_Statue_Text_0:
	.string "{PLAYER}: It looks like a... Question mark?\nWhat's that?$"

AlphRuins_Text_Exclamation_Statue_Text_0:
	.string "{PLAYER}: It looks like an... Exclamation mark?\nWhat's that?$"
