VioletSchool_MapScripts::
	.byte 0


VioletSchool_Text_Blackboard::
	msgbox VioletSchool_Text_Blackboard_Text_0, MSGBOX_SIGN
	end


VioletSchool_Text_Teacher::
	msgbox VioletSchool_Text_Teacher_Text_0, MSGBOX_NPC
	end


VioletSchool_Text_Kris::
	msgbox VioletSchool_Text_Kris_Text_0, MSGBOX_NPC
	end


VioletSchool_Text_Bugcatcher::
	msgbox VioletSchool_Text_Bugcatcher_Text_0, MSGBOX_NPC
	end


VioletSchool_Text_Youngster::
	msgbox VioletSchool_Text_Youngster_Text_0, MSGBOX_NPC
	end


VioletSchool_Text_Kid::
	msgbox VioletSchool_Text_Kid_Text_0, MSGBOX_NPC
	end


VioletSchool_Text_Blackboard_Text_0:
	.string "The blackboard is full of things you\nalready knows.$"

VioletSchool_Text_Teacher_Text_0:
	.string "Hello youngster. Have you done your\nhomework?\l……… ……… ……… ………\lOh wahoo so much BADGES!! I guess you\ldon't need to do your homework.$"

VioletSchool_Text_Kris_Text_0:
	.string "{PLAYER}: ……… ……… ……… ……… ……… ……… ………\pKRIS : ……… ……… ……… ……… ………… ……… ………$"

VioletSchool_Text_Bugcatcher_Text_0:
	.string "I'm taking notes of the teacher's\nlecture.\lI'd better copy the stuff on the\lblackboard too.$"

VioletSchool_Text_Youngster_Text_0:
	.string "A POKéMON holding a BERRY will heal\nitself in BATTLE.\lMany other items can be held by\lPOKéMON…\lIt sure is tough taking notes…$"

VioletSchool_Text_Kid_Text_0:
	.string "Oh no, I'm note taking notes.\nThe teacher told me to prevent anybody\lfrom moving upstairs.$"
