SlateportDocks2_MapScripts::
	.byte 0


SlateportDocks_Text_Worker::
	lock
	faceplayer
	msgbox SlateportDocks_Text_Worker_Text_0
	release
	end


SlateportDocks_Text_Sailor::
	lock
	faceplayer
	msgbox SlateportDocks_Text_Sailor_Text_0
	release
	end


SlateportDocks_Text_Camper::
	lock
	faceplayer
	msgbox SlateportDocks_Text_Camper_Text_0
	release
	end


SlateportDocks_Text_Woman::
	lock
	faceplayer
	msgbox SlateportDocks_Text_Woman_Text_0
	release
	end


SlateportDocks_Text_BlackBelt::
	lock
	faceplayer
	msgbox SlateportDocks_Text_BlackBelt_Text_0
	release
	end


SlateportDocks_Text_Worker_Text_0:
	.string "I have to fix the warehouse. Somehow,\n"
	.string "they decide to build it close to a WILD\l"
	.string "POKéMON nest!$"

SlateportDocks_Text_Sailor_Text_0:
	.string "This extension of SLATEPORT CITY was\n"
	.string "built to assure international shipping!$"

SlateportDocks_Text_Camper_Text_0:
	.string "Mmmpf ! I was recruit to prevent WILD\n"
	.string "POKéMON from running into the CITY but\l"
	.string "all my TEAM is out...$"

SlateportDocks_Text_Woman_Text_0:
	.string "I really want to go to KANTO, but the\n"
	.string "SAILOR inside can't unless you are\l"
	.string "strong enough or have a TICKET. But\l"
	.string "They sold it all...$"

SlateportDocks_Text_BlackBelt_Text_0:
	.string "Here is one of the best place to train\n"
	.string "alone in all HOENN ! By the way, what are\l"
	.string "you doing here ? You disturb me!$"
