MahoganyInn_MapScripts::
	.byte 0


MahoganyInn_Text_Monk::
	msgbox MahoganyInn_Text_Monk_Text_0, MSGBOX_NPC
	end


MahoganyInn_Text_Hiker::
	msgbox MahoganyInn_Text_Hiker_Text_0, MSGBOX_NPC
	end


MahoganyInn_Text_Camper::
	msgbox MahoganyInn_Text_Camper_Text_0, MSGBOX_NPC
	end


MahoganyInn_Text_Picnicker::
	msgbox MahoganyInn_Text_Picnicker_Text_0, MSGBOX_NPC
	end


MahoganyInn_Text_Monk_Text_0:
	.string "Welcome young TRAINER.\nAlas, you won't be able to rest here.\lIt's full.$"

MahoganyInn_Text_Hiker_Text_0:
	.string "I'm thinking of going through the ICE\nPATH.\lI need some extreme preparation!\lI really hate coldness.$"

MahoganyInn_Text_Camper_Text_0:
	.string "I don't really like the fact of resting\nin a INN.\lI prefere being surround by nature!$"

MahoganyInn_Text_Picnicker_Text_0:
	.string "If you had the chance to eat some RAGE\nCANDY, you'd be shocked by the taste!\lIt taste a bit like fish, but in a good\lway.$"
