SlateportCity_Wharehouse_MapScripts::
	.byte 0


SlateportCityWarehouse_Text_Policeman::
	lock
	faceplayer
	msgbox SlateportCityWarehouse_Text_Policeman_Text_0
	release
	end


SlateportCityWarehouse_Text_Sailor::
	lock
	faceplayer
	msgbox SlateportCityWarehouse_Text_Sailor_Text_0
	release
	end


SlateportCityWarehouse_Text_Worker::
	lock
	faceplayer
	msgbox SlateportCityWarehouse_Text_Worker_Text_0
	release
	end


SlateportCityWarehouse_Text_SalaryMan::
	lock
	faceplayer
	msgbox SlateportCityWarehouse_Text_SalaryMan_Text_0
	release
	end


SlateportCityWarehouse_Text_Scientist1::
	lock
	faceplayer
	msgbox SlateportCityWarehouse_Text_Scientist1_Text_0
	release
	end


SlateportCityWarehouse_Text_Scientist2::
	lock
	faceplayer
	msgbox SlateportCityWarehouse_Text_Scientist2_Text_0
	release
	end


SlateportCityWarehouse_Text_Scientist3_4::
	lock
	msgbox SlateportCityWarehouse_Text_Scientist3_4_Text_0
	release
	end


SlateportCityWarehouse_Text_Policeman_Text_0:
	.string "I'm sorry to tell you that you cannot go\n"
	.string "further. It's restricted to people\l"
	.string "working here.$"

SlateportCityWarehouse_Text_Sailor_Text_0:
	.string "Hey, what are you doing here ? I\n"
	.string "thought people couldn't run inside\l"
	.string "freely !$"

SlateportCityWarehouse_Text_Worker_Text_0:
	.string "You know Capt. STERNS ? He was working\n"
	.string "here before, and moved to the HARBOR\l"
	.string "because he got funds from DEVON for a\l"
	.string "Research and Development program.$"

SlateportCityWarehouse_Text_SalaryMan_Text_0:
	.string "I'm trying to learn every specificities\n"
	.string "the SHIPS have because I'll sell them\l"
	.string "across the WORLD. But it's very\l"
	.string "complicated...$"

SlateportCityWarehouse_Text_Scientist1_Text_0:
	.string "You know the big sound the SHIPS those\n"
	.string "when they leave the DOCKS ? I'm trying\l"
	.string "to find the right frequency to avoid\l"
	.string "disturbing the POKéMON. But it's hard\l"
	.string "because the best frequeces are the\l"
	.string "one ZUBAT are using.$"

SlateportCityWarehouse_Text_Scientist2_Text_0:
	.string "Oh I can see that you have a POKéDEX !\n"
	.string "PROF BIRCH gave it to you ? You have to\l"
	.string "run some errands for him right ?\l"
	.string "Hahaha, he never changes !$"

SlateportCityWarehouse_Text_Scientist3_4_Text_0:
	.string ".....................................\n"
	.string "{PLAYER} : This person seems very\l"
	.string "busy.$"
