Schools_MapScripts::
	.byte 0

Schools_Text_Teacher::
	lock
	faceplayer
	msgbox Schools_Text_Teacher_Text_0
	release
	end


Schools_Text_StudentF::
	lock
	faceplayer
	msgbox Schools_Text_StudentF_Text_0
	release
	end


Schools_Text_DisturbingGirl1::
	lock
	msgbox Schools_Text_DisturbingGirl1_Text_0
	release
	end


Schools_Text_DisturbingGirl2::
	lock
	msgbox Schools_Text_DisturbingGirl2_Text_0
	release
	end


Schools_Text_Creep::
	lock
	faceplayer
	msgbox Schools_Text_Creep_Text_0
	release
	end


Schools_Text_GoodStudent::
	lock
	msgbox Schools_Text_GoodStudent_Text_0
	release
	end


Schools_Text_BugStudent::
	lock
	faceplayer
	msgbox Schools_Text_BugStudent_Text_0
	release
	end


Schools_Text_StudentM::
	lock
	faceplayer
	msgbox Schools_Text_StudentM_Text_0
	release
	end


Schools_Text_StudentM2::
	lock
	faceplayer
	msgbox Schools_Text_StudentM2_Text_0
	release
	end


Schools_Text_Teacher_Text_0:
	.string "I only wish the kids would pay\n"
	.string "attention in the class...$"

Schools_Text_StudentF_Text_0:
	.string "It's not that it's boring, but honestly,\n"
	.string "why would I pay attention to something\l"
	.string "I already know :\n"
	.string "When you are poisoned, you lose HP.\p"
	.string "Oh come on, I want to catch a\n"
	.string "LENGENDARY POKEMON or something...$"

Schools_Text_DisturbingGirl1_Text_0:
	.string "YEAH ! Smash that button and finish him\n"
	.string "!$"

Schools_Text_DisturbingGirl2_Text_0:
	.string "Use fatality pleeeeeease, I want some\n"
	.string "blood !$"

Schools_Text_Creep_Text_0:
	.string "{PLAYER}: And I guess you are a\n"
	.string "student too ?\p"
	.string "Creepy guy : Hummm yes !... I want to\n"
	.string "know more about baby POKEMON.\p"
	.string "{PLAYER}: Degenerate...$"

Schools_Text_GoodStudent_Text_0:
	.string "And to cure a POKEMON from being\n"
	.string "poisoned, we can use an ANTIDOTE.\p"
	.string "SIR SIR ! Can I read about sleeping\n"
	.string "status ?$"

Schools_Text_BugStudent_Text_0:
	.string "The guy over there is such a sucker...\n"
	.string "Tomorrow, I'll beat him with my PINSIR.\l"
	.string "I'll see who's the best.$"

Schools_Text_StudentM_Text_0:
	.string "I'm busy studying............................No I'm\n"
	.string "kidding, I'm bore as fuck. I want a\l"
	.string "cigarette.\p"
	.string "{PLAYER}: Excuse me ?!$"

Schools_Text_StudentM2_Text_0:
	.string "When I'll grow up, I will ride a lot of\n"
	.string "GYARADOS and ravage the world.\p"
	.string "Nobody would defy me.\p"
	.string "{PLAYER}: OKAY... Well I'm leaving...$"
