VioletCityIndoor_MapScripts::
	.byte 0


VioletCityInside_Text_KrisMom::
	msgbox VioletCityInside_Text_KrisMom_Text_0, MSGBOX_NPC
	end


VioletCityInside_Text_LittleBoy::
	msgbox VioletCityInside_Text_LittleBoy_Text_0, MSGBOX_NPC
	release
	end


VioletCityInside_Text_BaldMan::
	msgbox VioletCityInside_Text_BaldMan_Text_0, MSGBOX_NPC
	end


VioletCityInside_Text_Birdkeeper::
	msgbox VioletCityInside_Text_Birdkeeper_Text_0, MSGBOX_NPC
	end


VioletCityInside_Text_Lass::
	msgbox VioletCityInside_Text_Lass_Text_0, MSGBOX_NPC
	end


VioletCityInside_Text_Lady::
	msgbox VioletCityInside_Text_Lady_Text_0, MSGBOX_NPC
	end


VioletCityInside_Text_Cooltrainer::
	msgbox VioletCityInside_Text_Cooltrainer_Text_0, MSGBOX_NPC
	end


VioletCityInside_Text_KrisMom_Text_0:
	.string "Oh hello!\nDo you go to EARL's SCHOOL? No?\lYou probably don't know my daughter\lKRIS.\lShe's the best student! We are very\lproud of her in VIOLET CITY!$"

VioletCityInside_Text_LittleBoy_Text_0:
	.string "I want a POKéMON to TRADE it but my\ndad says I'm too young...\lSIGH...$"

VioletCityInside_Text_BaldMan_Text_0:
	.string "You know that traded POKéMON grow\nquicker?\lYeah?\lAnd that you need certains BADGES\lotherwise they won't obey you?\lYEAH?!\lDamn it!\lKids nowadays are so smart!$"

VioletCityInside_Text_Birdkeeper_Text_0:
	.string "The ZEPHYR BADGE is named after an\nancient god of the west wind.\lVery fitting for the FLYING type GYM.$"

VioletCityInside_Text_Lass_Text_0:
	.string "BELLSPROUT is a popular POKéMON in this\ntown.\lIt doesn't do well against our GYM\lLEADER, though...$"

VioletCityInside_Text_Lady_Text_0:
	.string "I heard of a dancing tree.\nOdd isn't it?$"

VioletCityInside_Text_Cooltrainer_Text_0:
	.string "WALKNER, FALKNER's dad is currently\ntraveling around the world.\lThat's why the GYM is closed.\lI wonder where he is currently?$"
