#ifndef GUARD_CONSTANTS_DNS_UTILS_H
#define GUARD_CONSTANTS_DNS_UTILS_H

#define TIME_MIDNIGHT 0
#define TIME_DAWN 1
#define TIME_DAY 2
#define TIME_SUNSET 3
#define TIME_NIGHTFALL 4
#define TIME_NIGHT 5

#endif /* GUARD_CONSTANTS_DNS_UTILS_H */