LavenderMrFujiHouse_MapScripts::
	.byte 0


LavendarMrFujiHouse_Text_Psyduck::
	playmoncry SPECIES_PSYDUCK, CRY_MODE_NORMAL
	msgbox LavendarMrFujiHouse_Text_Psyduck_Text_0, MSGBOX_NPC
	end


LavendarMrFujiHouse_Text_Youngster::
	msgbox LavendarMrFujiHouse_Text_Youngster_Text_0, MSGBOX_NPC
	end


LavendarMrFujiHouse_Text_MrFuji::
	msgbox LavendarMrFujiHouse_Text_MrFuji_Text_0, MSGBOX_NPC
	end


LavendarMrFujiHouse_Text_Girl::
	msgbox LavendarMrFujiHouse_Text_Girl_Text_0, MSGBOX_NPC
	end


LavendarMrFujiHouse_Text_Boy::
	msgbox LavendarMrFujiHouse_Text_Boy_Text_0, MSGBOX_NPC
	end


LavendarMrFujiHouse_Text_Psyduck_Text_0:
	.string "PSYDUCK: Kwak?\pThe PSYDUCK is chokeg while being hugged\nby the kid.$"

LavendarMrFujiHouse_Text_Youngster_Text_0:
	.string "MR. FUJI had been praying alone\nfor CUBONE's mother.$"

LavendarMrFujiHouse_Text_MrFuji_Text_0:
	.string "Who are you?\p… … … … … … … … … … … … … … … … … … … …\l… … … … … … … … … … … … … … … … … … … …\pOh you too are on a POKéDEX quest?\lThe former CHAMPION, BLUE was on this\lquest too.\lI saw him in the POKéMON TOWER…\lYou should go see him, maybe he will\lhelp you in your quest.$"

LavendarMrFujiHouse_Text_Girl_Text_0:
	.string "This is really MR. FUJI's house.\pHe's really kind.\pHe looks after abandoned and\norphaned POKéMON.$"

LavendarMrFujiHouse_Text_Boy_Text_0:
	.string "It's so warm!\nPOKéMON are so nice to hug.$"
