HoennAirport_Inside_MapScripts::
	.byte 0


HoennAirport_Text_Hostress::
	lock
	faceplayer
	msgbox HoennAirport_Text_Hostress_Text_0
	release
	end


HoennAirport_Text_Policeman::
	lock
	faceplayer
	msgbox HoennAirport_Text_Policeman_Text_0
	release
	end


HoennAirport_Text_Artist::
	lock
	msgbox HoennAirport_Text_Artist_Text_0
	release
	end


HoennAirport_Text_Beauty::
	lock
	faceplayer
	msgbox HoennAirport_Text_Beauty_Text_0
	release
	end


HoennAirport_Text_Camper::
	lock
	faceplayer
	msgbox HoennAirport_Text_Camper_Text_0
	release
	end


HoennAirport_Text_Beauty2::
	lock
	faceplayer
	msgbox HoennAirport_Text_Beauty2_Text_0
	release
	end


HoennAirport_Text_FatMan::
	lock
	faceplayer
	msgbox HoennAirport_Text_FatMan_Text_0
	release
	end


HoennAirport_Text_OldWoman::
	lock
	faceplayer
	msgbox HoennAirport_Text_OldWoman_Text_0
	release
	end


HoennAirport_Text_FightGirl::
	lock
	faceplayer
	msgbox HoennAirport_Text_FightGirl_Text_0
	release
	end


HoennAirport_Text_OldMan::
	lock
	faceplayer
	msgbox HoennAirport_Text_OldMan_Text_0
	release
	end


HoennAirport_Text_Girl::
	lock
	faceplayer
	msgbox HoennAirport_Text_Girl_Text_0
	release
	end


HoennAirport_Text_Boy::
	lock
	faceplayer
	msgbox HoennAirport_Text_Boy_Text_0
	release
	end


HoennAirport_Text_Hostress_Text_0:
	.string "Welcome to HOENN AIRLINE did you have\n"
	.string "a reservation ? No ? Well we can't allow\l"
	.string "you to use our ABRA service to travel.\p"
	.string "Have a nice day.$"

HoennAirport_Text_Policeman_Text_0:
	.string "{PLAYER} : This area is restricted to\n"
	.string "authorized people only. Yeah I know !$"

HoennAirport_Text_Artist_Text_0:
	.string "Why is my flight not announce yet ?$"

HoennAirport_Text_Beauty_Text_0:
	.string "The ABRA service is really conveniant,\n"
	.string "it takes you everywhere ! Even in\l"
	.string "RHODES, but except for the COLOSSEUM\l"
	.string "who really want to visit this place...$"

HoennAirport_Text_Camper_Text_0:
	.string "It's the first time I'm gonna get\n"
	.string "teleported without being fainted! I so\l"
	.string "excited !$"

HoennAirport_Text_Beauty2_Text_0:
	.string "I came here for shopping but I'm a bit\n"
	.string "disappointed, I thought HOENN had way\l"
	.string "more stuff. I'm going back to KANTO.$"

HoennAirport_Text_FatMan_Text_0:
	.string "I swear I came with my daughter...$"

HoennAirport_Text_OldWoman_Text_0:
	.string "Sigh... Taking the SHIP is way more\n"
	.string "interesting than that !$"

HoennAirport_Text_FightGirl_Text_0:
	.string "HOENN is known for it formidable\n"
	.string "training grounds. I will train like never\l"
	.string "here !$"

HoennAirport_Text_OldMan_Text_0:
	.string "I spend my time having meeting here and\n"
	.string "there. What an incredible life I have !$"

HoennAirport_Text_Girl_Text_0:
	.string "We are taking a bus to travel to HOENN,\n"
	.string "but I don't think there is a place were\l"
	.string "the cars are driving right ?$"

HoennAirport_Text_Boy_Text_0:
	.string "I wish the journey will be fine and we\n"
	.string "are not being stuck in some alternate\l"
	.string "dimension !$"
