LavendarTown_MapScripts::
	.byte 0


LavenderTown_Text_CitySign::
	lock
	msgbox LavenderTown_Text_CitySign_Text_0
	release
	end


LavenderTown_Text_Channeler::
	lock
	faceplayer
	msgbox LavenderTown_Text_Channeler_Text_0
	release
	end


LavenderTown_Text_Girl::
	lock
	faceplayer
	msgbox LavenderTown_Text_Girl_Text_0
	release
	end


LavenderTown_Text_VolunteerSign::
	lock
	msgbox LavenderTown_Text_VolunteerSign_Text_0
	release
	end


LavenderTown_Text_pkmnTowerSign::
	lock
	msgbox LavenderTown_Text_pkmnTowerSign_Text_0
	release
	end


LavenderTown_Text_Guy::
	lock
	faceplayer
	msgbox LavenderTown_Text_Guy_Text_0
	release
	end


LavenderTown_Text_Birdkeeper::
	lock
	faceplayer
	msgbox LavenderTown_Text_Birdkeeper_Text_0
	release
	end


LavenderTown_Text_OldMan::
	lock
	faceplayer
	msgbox LavenderTown_Text_OldMan_Text_0
	release
	end


LavenderTown_Text_CitySign_Text_0:
	.string "LAVENDAR TOWN\n"
	.string "The Noble Purple Town$"

LavenderTown_Text_Channeler_Text_0:
	.string "Ghosts appeared in the POKéMON TOWER.\n"
	.string "I think they're the spirits of POKéMON\l"
	.string "that the ROCKETS killed.$"

LavenderTown_Text_Girl_Text_0:
	.string "My MOM told me that I can see things.\n"
	.string "For example there is a big entity over\l"
	.string "your head. But I guess i'ts a prank\l"
	.string "right ?$"

LavenderTown_Text_VolunteerSign_Text_0:
	.string "LAVENDAR Volunteer POKéMON House$"

LavenderTown_Text_pkmnTowerSign_Text_0:
	.string "May the souls of POKéMON rest easy.\n"
	.string "POKéMON TOWER$"

LavenderTown_Text_Guy_Text_0:
	.string "This town is known as the grave site of\n"
	.string "POKéMON. Memorial services are held in\l"
	.string "POKéMON TOWER.$"

LavenderTown_Text_Birdkeeper_Text_0:
	.string "I flew here as soon as I've learned that\n"
	.string "my sweet SPEAROW was sick... I guess\l"
	.string "now he isn't.$"

LavenderTown_Text_OldMan_Text_0:
	.string "Heard about Mr. FUJI ? He's a good guy\n"
	.string "that take care of the sick POKéMON.$"
