VioletCity_MapScripts::
	.byte 0


VioletCity_Text_Lass::
	lock
	faceplayer
	msgbox VioletCity_Text_Lass_Text_0
	release
	end


VioletCity_Text_TownSign::
	lock
	faceplayer
	msgbox VioletCity_Text_TownSign_Text_0
	release
	end


VioletCity_Text_Youngster::
	lock
	faceplayer
	msgbox VioletCity_Text_Youngster_Text_0
	release
	end


VioletCity_Text_OldMan::
	lock
	faceplayer
	msgbox VioletCity_Text_OldMan_Text_0
	release
	end


VioletCity_Text_SproutTowerSign::
	lock
	faceplayer
	msgbox VioletCity_Text_SproutTowerSign_Text_0
	release
	end


VioletCity_Text_Lass2::
	lock
	faceplayer
	msgbox VioletCity_Text_Lass2_Text_0
	release
	end


VioletCity_Text_Sage1::
	lock
	faceplayer
	msgbox VioletCity_Text_Sage1_Text_0
	release
	end


VioletCity_Text_Sage2::
	lock
	faceplayer
	msgbox VioletCity_Text_Sage2_Text_0
	release
	end


VioletCity_Text_Camper::
	lock
	faceplayer
	msgbox VioletCity_Text_Camper_Text_0
	release
	end


VioletCity_Text_GymSign::
	lock
	faceplayer
	msgbox VioletCity_Text_GymSign_Text_0
	release
	end


VioletCity_Text_SchoolSign::
	lock
	faceplayer
	msgbox VioletCity_Text_SchoolSign_Text_0
	release
	end


VioletCity_Text_Pidgey::
	lock
	faceplayer
	playmoncry SPECIES_PIDGEY, CRY_MODE_NORMAL
	msgbox VioletCity_Text_Pidgey_Text_0
	release
	end


VioletCity_Text_Pidgeotto::
	lock
	faceplayer
	playmoncry SPECIES_PIDGEOTTO, CRY_MODE_NORMAL
	msgbox VioletCity_Text_Pidgeotto_Text_0
	release
	end


VioletCity_Text_KrisSign::
	lock
	faceplayer
	msgbox VioletCity_Text_KrisSign_Text_0
	release
	end


VioletCity_Text_Lass_Text_0:
	.string "Ghosts are rumored to appear in SPROUT\n"
	.string "TOWER. They said normal Type POKéMON\l"
	.string "moves had no effect on Ghosts.$"

VioletCity_Text_TownSign_Text_0:
	.string "VIOLET CITY\p"
	.string "The City of Nostalgic Scents$"

VioletCity_Text_Youngster_Text_0:
	.string "Hey, you're a POKéMON TRAINER ? If you\n"
	.string "want to check the CITY's GYM LEADER,\l"
	.string "he's travelling. I heard his son\l"
	.string "FALKNER is going to be the next\l"
	.string "LEADER, but he is training in the\l"
	.string "SPROUT TOWER.$"

VioletCity_Text_OldMan_Text_0:
	.string "I'm EARL and This is VIOLET CITY's\n"
	.string "ACADEMY. We teach the basic for the\l"
	.string "future TRAINERS !$"

VioletCity_Text_SproutTowerSign_Text_0:
	.string "SPROUT TOWER\p"
	.string "Experience the Way of the POKéMON$"

VioletCity_Text_Lass2_Text_0:
	.string "Look at those PIDGEY !$"

VioletCity_Text_Sage1_Text_0:
	.string "We are all waiting for FALKNER to finish\n"
	.string "his training in the SPROUT TOWER to\l"
	.string "open the GYM.$"

VioletCity_Text_Sage2_Text_0:
	.string "Here is the SPROUT TOWER. Please pay\n"
	.string "respect to my colleague inside and the\l"
	.string "wild POKéMON.$"

VioletCity_Text_Camper_Text_0:
	.string "Head south and you'll reach the RUIN OF\n"
	.string "ALPH.$"

VioletCity_Text_GymSign_Text_0:
	.string "VIOLET TOWN POKéMON Gym LEADER:\n"
	.string "FALKNER\n"
	.string "The Elegant Master of Flying POKéMON$"

VioletCity_Text_SchoolSign_Text_0:
	.string "EARL's POKéMON Academy$"

VioletCity_Text_Pidgey_Text_0:
	.string "Piii !$"

VioletCity_Text_Pidgeotto_Text_0:
	.string "Tooo Piii !$"

VioletCity_Text_KrisSign_Text_0:
	.string "KRIS' HOUSE$"
