Route18Doors_MapScripts::
	.byte 0


Route18_EastEntrance_2F_Text_PalletTownInWest::
	msgbox Route18_EastEntrance_2F_Text_PalletTownInWest_Text_0, MSGBOX_AUTOCLOSE
	end


Route18_EastEntrance_2F_Text_PeopleSwimming::
	msgbox Route18_EastEntrance_2F_Text_PeopleSwimming_Text_0, MSGBOX_AUTOCLOSE
	end


Route18_EastEntrance_1F_Text_Guard::
	msgbox Route18_EastEntrance_1F_Text_Guard_Text_0, MSGBOX_NPC
	end


Route18_EastEntrance_2F_Text_PalletTownInWest_Text_0:
	.string "Let's see what the binoculars have\nto show…\pPALLET TOWN is in the west.$"

Route18_EastEntrance_2F_Text_PeopleSwimming_Text_0:
	.string "Let's see what the binoculars have\nto show…\pThere are people swimming.$"

Route18_EastEntrance_1F_Text_Guard_Text_0:
	.string "CYCLING ROAD is all uphill from\nhere.$"
