FortreeCity_School_MapScripts::
	.byte 0


FortreeCity_School_Youngster::
	msgbox FortreeCity_School_Youngster_Text_0, MSGBOX_NPC
	end


FortreeCity_School_Teacher::
	msgbox FortreeCity_School_Teacher_Text_0, MSGBOX_NPC
	end


FortreeCity_School_Lass::
	msgbox FortreeCity_School_Lass_Text_0, MSGBOX_NPC
	end


FortreeCity_School_SmallGirl::
	msgbox FortreeCity_School_SmallGirl_Text_0, MSGBOX_NPC
	end


FortreeCity_School_Youngster_Text_0:
	.string "I really hate SWAGGER!\nMy POKéMON always hurt itself while\lconfused.$"

FortreeCity_School_Teacher_Text_0:
	.string "WINONA studied here. She really was the\nbest!\lShe learnt a lot on a hill, where a lot\lof FLYING types POKéMON are living.$"

FortreeCity_School_Lass_Text_0:
	.string "I had a BIKE but it's lost somewhere in\nthe bushes...$"

FortreeCity_School_SmallGirl_Text_0:
	.string "I have a golden MAGIKARP! Can you\nbelieve that?$"
