Mossdeep_SeaGate1_MapScripts::
	.byte 0


Mossdeep_SeaGate1_Attendant::
	msgbox Mossdeep_SeaGate1_Attendant_Text_0, MSGBOX_NPC
	end


Mossdeep_SeaGate1_Gentleman::
	msgbox Mossdeep_SeaGate1_Gentleman_Text_0, MSGBOX_NPC
	end


Mossdeep_SeaGate1_Growlithe::
	playmoncry SPECIES_GROWLITHE, CRY_MODE_NORMAL
	msgbox Mossdeep_SeaGate1_Growlithe_Text_0, MSGBOX_NPC
	end


Mossdeep_SeaGate1_Policeman::
	msgbox Mossdeep_SeaGate1_Policeman_Text_0, MSGBOX_NPC
	end


Mossdeep_SeaGate1_Beauty::
	msgbox Mossdeep_SeaGate1_Beauty_Text_0, MSGBOX_NPC
	end


Mossdeep_SeaGate1_Woman::
	msgbox Mossdeep_SeaGate1_Woman_Text_0, MSGBOX_NPC
	end


Mossdeep_SeaGate1_Man::
	msgbox Mossdeep_SeaGate1_Man_Text_0, MSGBOX_NPC
	end


Mossdeep_SeaGate1_Artist::
	msgbox Mossdeep_SeaGate1_Artist_Text_0, MSGBOX_NPC
	end


Mossdeep_SeaGate1_Attendant_Text_0:
	.string "Go through this gate to end up in the\ndocks.$"

Mossdeep_SeaGate1_Gentleman_Text_0:
	.string "I'm travelling the world with my\nPOKéMON.\lI'm came from KANTO with the SS ANNE.\lI'll stay around for a few moment and\lthen probably move to UNOVA.$"

Mossdeep_SeaGate1_Growlithe_Text_0:
	.string "Graou!$"

Mossdeep_SeaGate1_Policeman_Text_0:
	.string "I'm here just in case something happen.\n{PLAYER}: Like an attack on the space\lstation?$"

Mossdeep_SeaGate1_Beauty_Text_0:
	.string "I don't know how the ferry system is\nworking here. It's a bit confusing.\lShouldn't we simply use FLY?$"

Mossdeep_SeaGate1_Woman_Text_0:
	.string "My brother is living in LILYCOVE. I\nheard there is a great contest place.\lI can't wait!$"

Mossdeep_SeaGate1_Man_Text_0:
	.string "I'm representing a company from\nSINNOH.\lWe are working on a watch. I have an\lappointment with the DEVON company. We\lare sharing innovations!$"

Mossdeep_SeaGate1_Artist_Text_0:
	.string "The landscape is awesome.\nI wish I could go on the roof of the\lspace center to capture the light!$"
