VictoryRoad_2F_MapScripts::
	.byte 0


VictoryRoad2F_Text_CooltrainerF::
	trainerbattle_single TRAINER_LILA_AND_ROY_2, VictoryRoad2F_Text_CooltrainerF_Text_0, VictoryRoad2F_Text_CooltrainerF_Text_1
	msgbox VictoryRoad2F_Text_CooltrainerF_Text_2, MSGBOX_AUTOCLOSE
	end


VictoryRoad2F_Text_CooltrainerM::
	trainerbattle_single TRAINER_LILA_AND_ROY_3, VictoryRoad2F_Text_CooltrainerM_Text_0, VictoryRoad2F_Text_CooltrainerM_Text_1
	msgbox VictoryRoad2F_Text_CooltrainerM_Text_2, MSGBOX_AUTOCLOSE
	end


VictoryRoad2F_Text_ExpertM::
	trainerbattle_single TRAINER_LILA_AND_ROY_4, VictoryRoad2F_Text_ExpertM_Text_0, VictoryRoad2F_Text_ExpertM_Text_1
	msgbox VictoryRoad2F_Text_ExpertM_Text_2, MSGBOX_AUTOCLOSE
	end


VictoryRoad2F_Text_CooltrainerM2::
	trainerbattle_single TRAINER_CRISTIN_2, VictoryRoad2F_Text_CooltrainerM2_Text_0, VictoryRoad2F_Text_CooltrainerM2_Text_1
	msgbox VictoryRoad2F_Text_CooltrainerM2_Text_2, MSGBOX_AUTOCLOSE
	end


VictoryRoad2F_Text_ExpertF::
	trainerbattle_single TRAINER_CRISTIN_3, VictoryRoad2F_Text_ExpertF_Text_0, VictoryRoad2F_Text_ExpertF_Text_1
	msgbox VictoryRoad2F_Text_ExpertF_Text_2, MSGBOX_AUTOCLOSE
	end


VictoryRoad2F_Text_CooltrainerF_Text_0:
	.string "I'm lost but I'm strong.$"

VictoryRoad2F_Text_CooltrainerF_Text_1:
	.string "Well you were stronger !$"

VictoryRoad2F_Text_CooltrainerF_Text_2:
	.string "You should but careful, I've heard that\n"
	.string "some guys are pissed because they are\l"
	.string "lost. So they want to smash every\l"
	.string "TRAINER they see.$"

VictoryRoad2F_Text_CooltrainerM_Text_0:
	.string "I'm pissed, I need to punch something !$"

VictoryRoad2F_Text_CooltrainerM_Text_1:
	.string "Ahhhhhhhhhhhh !!!$"

VictoryRoad2F_Text_CooltrainerM_Text_2:
	.string "Yeah whatever, I don't care if I lost. I\n"
	.string "need to get out of here.$"

VictoryRoad2F_Text_ExpertM_Text_0:
	.string "Kid ! Admire the might of my friends !$"

VictoryRoad2F_Text_ExpertM_Text_1:
	.string "Well I'm the one admiring your strenght.$"

VictoryRoad2F_Text_ExpertM_Text_2:
	.string "I'm trying to meditate, but this chump\n"
	.string "is following me. I can't stand him...$"

VictoryRoad2F_Text_CooltrainerM2_Text_0:
	.string "A punk ! Let's fight !$"

VictoryRoad2F_Text_CooltrainerM2_Text_1:
	.string "I think I'm the punk...$"

VictoryRoad2F_Text_CooltrainerM2_Text_2:
	.string "What can I do now that a brat taught me\n"
	.string "a good lesson...$"

VictoryRoad2F_Text_ExpertF_Text_0:
	.string "Hello dear, you have some time for a\nlady ?$"

VictoryRoad2F_Text_ExpertF_Text_1:
	.string "Ah ! An heart attack !$"

VictoryRoad2F_Text_ExpertF_Text_2:
	.string "Fortunatly I have my pacemaker on me\n"
	.string "everyday.$"
