Route114_Indoors_MapScripts::
	.byte 0


Route114_Indoors_Text_Kindler::
	msgbox Route114_Indoors_Text_Kindler_Text_0, MSGBOX_NPC
	end


Route114_Indoors_Text_HikerKanto::
	msgbox Route114_Indoors_Text_HikerKanto_Text_0, MSGBOX_NPC
	end


Route114_Indoors_Text_Hiker::
	msgbox Route114_Indoors_Text_Hiker_Text_0, MSGBOX_NPC
	end


Route114_Indoors_Text_Kindler_Text_0:
	.string "No I'm not outside burning thing.\nCan I laze around please?$"

Route114_Indoors_Text_HikerKanto_Text_0:
	.string "I come from JOHTO. I came to see my\nfriend and tell him about the\lvery unsuspicious HIKERS CLUB.\lWhat are we?\lWell, just a HIKER group. We love the\lmountain.\lYep that's all!\lGoodbye now.$"

Route114_Indoors_Text_Hiker_Text_0:
	.string "You know the HIKER CLUB?\nNever heard of that.\lI hope that's not something like the\lTEAM WATER or something.\lA bunch of losers really.$"
