Route12Gate_MapScripts::
	.byte 0


Route12Gate_Text_Lass::
	msgbox Route12Gate_Text_Lass_Text_0, MSGBOX_NPC
	end


Route12Gate_Text_TheresManFishing::
	msgbox Route12Gate_Text_TheresManFishing_Text_0, MSGBOX_NPC
	end


Route12Gate_Text_ItsPokemonTower::
	msgbox Route12Gate_Text_ItsPokemonTower_Text_0, MSGBOX_NPC
	end


Route12Gate_Text_Police::
	msgbox Route12Gate_Text_Police_Text_0, MSGBOX_NPC
	end


Route12Gate_Text_Lass_Text_0:
	.string "My POKéMON's ashes are stored in\nPOKéMON TOWER.\pI saw the former CHAMPION, BLUE there.$"

Route12Gate_Text_TheresManFishing_Text_0:
	.string "Let's see what the binoculars have\nto show…\pThere's a man fishing!$"

Route12Gate_Text_ItsPokemonTower_Text_0:
	.string "Let's see what the binoculars have\nto show…\pIt's POKéMON TOWER!$"

Route12Gate_Text_Police_Text_0:
	.string "There's a lookout spot upstairs.\nThe view is magnificent.$"
