SlateportCity_Multiple_Houses_MapScripts::
	.byte 0


SlateportCity_Multiple_Houses_Text_GBABoy::
	lock
	faceplayer
	msgbox SlateportCity_Multiple_Houses_Text_GBABoy_Text_0
	release
	end


SlateportCity_Multiple_Houses_Text_Fisherman::
	lock
	faceplayer
	msgbox SlateportCity_Multiple_Houses_Text_Fisherman_Text_0
	release
	end


SlateportCity_Multiple_Houses_Text_Wingull::
	lock
	faceplayer
	playmoncry SPECIES_WINGULL, CRY_MODE_NORMAL
	msgbox SlateportCity_Multiple_Houses_Text_Wingull_Text_0
	release
	end


SlateportCity_Multiple_Houses_Text_Sailor::
	lock
	faceplayer
	msgbox SlateportCity_Multiple_Houses_Text_Sailor_Text_0
	release
	end


SlateportCity_Multiple_Houses_Text_SchoolBoyM::
	lock
	faceplayer
	msgbox SlateportCity_Multiple_Houses_Text_SchoolBoyM_Text_0
	release
	end


SlateportCity_Multiple_Houses_Text_OldMan::
	lock
	faceplayer
	msgbox SlateportCity_Multiple_Houses_Text_OldMan_Text_0
	release
	end


SlateportCity_Multiple_Houses_Text_Azurill::
	lock
	faceplayer
	playmoncry SPECIES_AZURILL, CRY_MODE_NORMAL
	msgbox SlateportCity_Multiple_Houses_Text_Azurill_Text_0
	release
	end


SlateportCity_Multiple_Houses_Text_RichBoy::
	lock
	faceplayer
	msgbox SlateportCity_Multiple_Houses_Text_RichBoy_Text_0
	release
	end


SlateportCity_Multiple_Houses_Text_Beauty::
	lock
	faceplayer
	msgbox SlateportCity_Multiple_Houses_Text_Beauty_Text_0
	release
	end


SlateportCity_Multiple_Houses_Text_BaldMan::
	lock
	faceplayer
	msgbox SlateportCity_Multiple_Houses_Text_BaldMan_Text_0
	release
	end


SlateportCity_Multiple_Houses_Text_LittleBoy::
	lock
	faceplayer
	msgbox SlateportCity_Multiple_Houses_Text_LittleBoy_Text_0
	release
	end


SlateportCity_Multiple_Houses_Text_LittleGirl::
	lock
	faceplayer
	msgbox SlateportCity_Multiple_Houses_Text_LittleGirl_Text_0
	release
	end


SlateportCity_Multiple_Houses_Text_TuberBoy::
	lock
	faceplayer
	msgbox SlateportCity_Multiple_Houses_Text_TuberBoy_Text_0
	release
	end


SlateportCity_Multiple_Houses_Text_GBABoy_Text_0:
	.string "You know what life is?\n"
	.string "Having a good game, and a bunch of\l"
	.string "amazing dolls!\l"
	.string "{PLAYER}: Seems pretty depressing\l"
	.string "yeah!$"

SlateportCity_Multiple_Houses_Text_Fisherman_Text_0:
	.string "I'm so freaking hungry!\n"
	.string "I need some FEEBAS ragout!\l"
	.string "Did you ever taste that?$"

SlateportCity_Multiple_Houses_Text_Wingull_Text_0:
	.string "Guul!\n"
	.string "{PLAYER}: I hope your trainer is\l"
	.string "gonna get something to eat.\l"
	.string "Otherwise, I've been happy to meet\l"
	.string "you.$"

SlateportCity_Multiple_Houses_Text_Sailor_Text_0:
	.string "You know, if you get eastward,\n"
	.string "you'll find the docks of\l"
	.string "SLATEPORT.\l"
	.string "You can take a ferry to KANTO.\l"
	.string "Yeah I've already taken it!$"

SlateportCity_Multiple_Houses_Text_SchoolBoyM_Text_0:
	.string "My dad went overseas when he was\n"
	.string "younger!\l"
	.string "He even went to UNOVA!\l"
	.string "I wanna go there too when I grew\l"
	.string "hope!$"

SlateportCity_Multiple_Houses_Text_OldMan_Text_0:
	.string "I used to be a famous sailor!\n"
	.string "You know BRINEY? He used to be my\l"
	.string "nemesis!\l"
	.string "After a fight he was exil on ROUTE\l"
	.string "104. That's how we used to live as\l"
	.string "sailors!\l"
	.string "Hahahahaha!$"

SlateportCity_Multiple_Houses_Text_Azurill_Text_0:
	.string "Zu zu!$"

SlateportCity_Multiple_Houses_Text_RichBoy_Text_0:
	.string "Have you ever been to the BATTLE\n"
	.string "TENT?\l"
	.string "It's so damn good!$"

SlateportCity_Multiple_Houses_Text_Beauty_Text_0:
	.string "I'm pretty sure there were some\n"
	.string "kind of CONTEST here...\l"
	.string "{PLAYER}: Maybe in an alternate\l"
	.string "reality were I'm dressed in red\l"
	.string "instead of green?$"

SlateportCity_Multiple_Houses_Text_BaldMan_Text_0:
	.string "I stayed in a inn for sometime,\n"
	.string "and I end up with three children!\l"
	.string "Just like when you let your\l"
	.string "POKéMON in the DAY CARE for too\l"
	.string "long!!$"

SlateportCity_Multiple_Houses_Text_LittleBoy_Text_0:
	.string "My mom left my dad because she got\n"
	.string "a career in KALOS.\l"
	.string "Sometime we got to see her. We can\l"
	.string "eat some croissant!\l"
	.string "That's so nice!$"

SlateportCity_Multiple_Houses_Text_LittleGirl_Text_0:
	.string "You know that you can feed your\n"
	.string "POKéMON with our food?\l"
	.string "Like SODA and pastries?\l"
	.string "I don't know if they would eat a\l"
	.string "sandwich made with POKéMON meat...$"

SlateportCity_Multiple_Houses_Text_TuberBoy_Text_0:
	.string "My POKéMON are ready to swim and\n"
	.string "so I am!$"
