Route11Gate_MapScripts::
	.byte 0


Route11Gate_Text_Policeman1::
	msgbox Route11Gate_Text_Policeman1_Text_0, MSGBOX_NPC
	end


Route11Gate_Text_Policeman2::
	msgbox Route11Gate_Text_Policeman2_Text_0, MSGBOX_NPC
	end


Route11Gate_Text_WhatABreathtakingView::
	msgbox Route11Gate_Text_WhatABreathtakingView_Text_0, MSGBOX_NPC
	end


Route11Gate_Text_RockTunnelGoodRouteToLavender::
	msgbox Route11Gate_Text_RockTunnelGoodRouteToLavender_Text_0, MSGBOX_NPC
	end


Route11Gate_Text_Scientist::
	msgbox Route11Gate_Text_Scientist_Text_0, MSGBOX_NPC
	end


Route11Gate_Text_Youngster::
	msgbox Route11Gate_Text_Youngster_Text_0, MSGBOX_NPC
	end


Route11Gate_Text_Policeman1_Text_0:
	.string "Don't you think it's hard to think\nup good names for POKéMON?\pEspecially if you've caught a\nwhole bunch?\pIn LAVENDER TOWN, there's a man\nwho rates POKéMON nicknames.\pHe can even help you rename your\nPOKéMON, too.$"

Route11Gate_Text_Policeman2_Text_0:
	.string "If you're aiming to reach LAVENDER\nTOWN, take ROCK TUNNEL.\pYou can get to ROCK TUNNEL from\nCERULEAN CITY.$"

Route11Gate_Text_WhatABreathtakingView_Text_0:
	.string "Let's see what the binoculars have\nto show…\pWhat a breathtaking view!$"

Route11Gate_Text_RockTunnelGoodRouteToLavender_Text_0:
	.string "Let's see what the binoculars have\nto show…\pTo get to LAVENDER TOWN from\nCERULEAN CITY…\pROCK TUNNEL appears to be a good\nroute to take.$"

Route11Gate_Text_Scientist_Text_0:
	.string "There are items on the ground that\nmay be hidden from view.\pUse the ITEMFINDER to detect any\nhidden items close to you.\pThe machine is a bit limited.\nIt can't pinpoint item locations.\pWhat it does is show the direction\nwhere the item is.\pUse it to get your bearings, then\nsearch the suspect area by hand.$"

Route11Gate_Text_Youngster_Text_0:
	.string "I traded my NIDORINA, but I don't think\nit was worth it...$"
