EcruteakCity_MapScripts::
	.byte 0


EcruteakCity_Text_Kimono::
	lock
	faceplayer
	msgbox EcruteakCity_Text_Kimono_Text_0
	release
	end


EcruteakCity_Text_Sage::
	lock
	faceplayer
	msgbox EcruteakCity_Text_Sage_Text_0
	release
	end


EcruteakCity_Text_Sage2::
	lock
	faceplayer
	msgbox EcruteakCity_Text_Sage2_Text_0
	release
	end


EcruteakCity_Text_WomanBeforeTower::
	lock
	faceplayer
	msgbox EcruteakCity_Text_WomanBeforeTower_Text_0
	release
	end


EcruteakCity_Text_Girl::
	lock
	faceplayer
	msgbox EcruteakCity_Text_Girl_Text_0
	release
	end


EcruteakCity_Text_BaldingMan::
	lock
	faceplayer
	msgbox EcruteakCity_Text_BaldingMan_Text_0
	release
	end


EcruteakCity_Text_FatMan1::
	lock
	faceplayer
	msgbox EcruteakCity_Text_FatMan1_Text_0
	release
	end


EcruteakCity_Text_Maniac::
	lock
	faceplayer
	msgbox EcruteakCity_Text_Maniac_Text_0
	release
	end


EcruteakCity_Text_OldMan::
	lock
	faceplayer
	msgbox EcruteakCity_Text_OldMan_Text_0
	release
	end


EcruteakCity_Text_BurnTower::
	lock
	msgbox EcruteakCity_Text_BurnTower_Text_0
	release
	end


EcruteakCity_Text_DanceTheater::
	lock
	msgbox EcruteakCity_Text_DanceTheater_Text_0
	release
	end


EcruteakCity_Text_CitySign::
	lock
	msgbox EcruteakCity_Text_CitySign_Text_0
	release
	end


EcruteakCity_Text_GymSign::
	lock
	msgbox EcruteakCity_Text_GymSign_Text_0
	release
	end


EcruteakCity_Text_Eevee::
	lock
	faceplayer
	playmoncry SPECIES_EEVEE, CRY_MODE_NORMAL
	msgbox EcruteakCity_Text_Eevee_Text_0
	release
	end


EcruteakCity_Text_Kimono_Text_0:
	.string "Here is the DANCE THEATER. You can\n"
	.string "enjoy some traditional dances inside.\l"
	.string "My colleagues are also TRAINERS. Be\l"
	.string "careful !$"

EcruteakCity_Text_Sage_Text_0:
	.string "The way to the TIN TOWER is closed,\n"
	.string "except for a TRAINER with a pure heart\l"
	.string "(But I don't think it exist...).$"

EcruteakCity_Text_Sage2_Text_0:
	.string "Hello ! The GYM is closed. Yeah I know...\n"
	.string "MORTIMER isn't inside so, what's the\l"
	.string "point of opening it...$"

EcruteakCity_Text_WomanBeforeTower_Text_0:
	.string "This tower is really gloomy. It give me\n"
	.string "chills... Brrrrrrrr !$"

EcruteakCity_Text_Girl_Text_0:
	.string "I'm about to practice my dancing skills\n"
	.string "in the DANCE THEATER. You think I'll\l"
	.string "need my EEVEE ?$"

EcruteakCity_Text_BaldingMan_Text_0:
	.string "ECRUTEAK use to have two towers : One\n"
	.string "in the east and another one in the\l"
	.string "west.$"

EcruteakCity_Text_FatMan1_Text_0:
	.string "In OLIVINE CITY there is a POKéMON\n"
	.string "named AMPHY that enlight the sea from\l"
	.string "the LIGHTHOUSE. I heard a girl named\l"
	.string "JASMINE is really close to this\l"
	.string "POKéMON.$"

EcruteakCity_Text_Maniac_Text_0:
	.string "I'm only here so sometime, but it feel\n"
	.string "like I've been trapped into a time\l"
	.string "portal. Look at this architecture !$"

EcruteakCity_Text_OldMan_Text_0:
	.string "I don't know why we are no rebuilding\n"
	.string "the BRASS TOWER.\p"
	.string "I mean look at this mess !$"

EcruteakCity_Text_BurnTower_Text_0:
	.string "BURNED TOWER\n"
	.string "It was destroyed by a mysterious fire.\l"
	.string "Please stay away, as it is unsafe.$"

EcruteakCity_Text_DanceTheater_Text_0:
	.string "ECRUTEAK DANCE THEATER$"

EcruteakCity_Text_CitySign_Text_0:
	.string "ECRUTEAK CITY\n"
	.string "A Historical City where the Past meets\l"
	.string "the Present.$"

EcruteakCity_Text_GymSign_Text_0:
	.string "ECRUTEAK CITY POKéMON GYM LEADER:\n"
	.string "MORTY\p"
	.string "The Mystic Seer of the Future.$"

EcruteakCity_Text_Eevee_Text_0:
	.string "Eeeevee !$"
