CaveOfOrigin_UnusedRubySapphireMap1_MapScripts::
	.byte 0


CeladonResto_Text_Hiker::
	lock
	faceplayer
	msgbox CeladonResto_Text_Hiker_Text_0
	release
	end


CeladonResto_Text_GymGuy::
	lock
	faceplayer
	msgbox CeladonResto_Text_GymGuy_Text_0
	release
	end


CeladonResto_Text_Fatman::
	lock
	faceplayer
	msgbox CeladonResto_Text_Fatman_Text_0
	release
	end


CeladonResto_Text_Woman::
	lock
	faceplayer
	msgbox CeladonResto_Text_Woman_Text_0
	release
	end


CeladonResto_Text_Cook::
	lock
	faceplayer
	msgbox CeladonResto_Text_Cook_Text_0
	release
	end


CeladonResto_Text_Hiker_Text_0:
	.string "Pssst ! There were a basement under the\n"
	.string "GAME CORNER.$"

CeladonResto_Text_GymGuy_Text_0:
	.string "I always thought I was going to get the\n"
	.string "three 7 ! Damn it GAME CORNER ! Damn it !$"

CeladonResto_Text_Fatman_Text_0:
	.string "Munch... The man at that table lost it\n"
	.string "all at the slots. He even gave his COIN\l"
	.string "CASE to some kid. He is dangerous !$"

CeladonResto_Text_Woman_Text_0:
	.string "My POKéMON are weak, so I often have to\n"
	.string "go to the Dug Store.$"

CeladonResto_Text_Cook_Text_0:
	.string "Huh ? What you want a SANDWICH ? We are\n"
	.string "taking a break so maybe later. Or not...$"
