CinnabarInside_MapScripts::
	.byte 0


CinnabarInside_Text_PhotoOfLabFounderDrFuji::
	msgbox CinnabarInside_Text_PhotoOfLabFounderDrFuji_Text_0, MSGBOX_SIGN
	end


CinnabarInside_Text_PokemonLab_Entrance_Text_StudyMonsExtensively::
	msgbox CinnabarInside_Text_PokemonLab_Entrance_Text_StudyMonsExtensively_Text_0, MSGBOX_NPC
	end


CinnabarInside_Text_Entrance_Text_MeetingRoomSign::
	msgbox CinnabarInside_Text_Entrance_Text_MeetingRoomSign_Text_0, MSGBOX_SIGN
	end


CinnabarInside_Text_RAndDRoomSign::
	msgbox CinnabarInside_Text_RAndDRoomSign_Text_0, MSGBOX_SIGN
	end


CinnabarInside_Text_TestingRoomSign::
	msgbox CinnabarInside_Text_TestingRoomSign_Text_0, MSGBOX_SIGN
	end


CinnabarInside_Text_FoundFossilInMtMoon::
	msgbox CinnabarInside_Text_FoundFossilInMtMoon_Text_0, MSGBOX_NPC
	end


CinnabarInside_Text_AnAmberPipe::
	msgbox CinnabarInside_Text_AnAmberPipe_Text_0, MSGBOX_SIGN
	end


CinnabarInside_Text_EeveeCanEvolveIntroThreeMons::
	msgbox CinnabarInside_Text_EeveeCanEvolveIntroThreeMons_Text_0, MSGBOX_NPC
	end


CinnabarInside_Text_LegendaryBirdEmail::
	msgbox CinnabarInside_Text_LegendaryBirdEmail_Text_0, MSGBOX_NPC
	end


CinnabarInside_Text_GuyGivingContext::
	msgbox CinnabarInside_Text_GuyGivingContext_Text_0, MSGBOX_NPC
	end


CinnabarInside_Text_Gentleman::
	msgbox CinnabarInside_Text_Gentleman_Text_0, MSGBOX_NPC
	end


CinnabarInside_Text_OldLady::
	msgbox CinnabarInside_Text_OldLady_Text_0, MSGBOX_NPC
	end


CinnabarInside_Text_PhotoOfLabFounderDrFuji_Text_0:
	.string "A photo of the LAB's founder…\nDR. FUJI?!$"

CinnabarInside_Text_PokemonLab_Entrance_Text_StudyMonsExtensively_Text_0:
	.string "We study POKéMON extensively\nevery day.\pPeople often bring us rare POKéMON\nfor examination.$"

CinnabarInside_Text_Entrance_Text_MeetingRoomSign_Text_0:
	.string "POKéMON LAB\nMeeting Room$"

CinnabarInside_Text_RAndDRoomSign_Text_0:
	.string "POKéMON LAB\nR & D Room$"

CinnabarInside_Text_TestingRoomSign_Text_0:
	.string "POKéMON LAB\nTesting Room$"

CinnabarInside_Text_FoundFossilInMtMoon_Text_0:
	.string "I found this most remarkable fossil\ninside MT. MOON.\pI think it's of a rare, prehistoric\nPOKéMON.$"

CinnabarInside_Text_AnAmberPipe_Text_0:
	.string "An amber pipe!$"

CinnabarInside_Text_EeveeCanEvolveIntroThreeMons_Text_0:
	.string "EEVEE can evolve into one of five\nkinds of POKéMON.$"

CinnabarInside_Text_LegendaryBirdEmail_Text_0:
	.string "There's an e-mail message.\p… … …\pThere are three legendary bird\nPOKéMON.\pThey are ARTICUNO, ZAPDOS, and\nMOLTRES.\pTheir whereabouts are unknown.\pWe plan to explore the cavern\nclose to CERULEAN.\pFrom: POKéMON RESEARCH TEAM…$"

CinnabarInside_Text_GuyGivingContext_Text_0:
	.string "Now that TEAM ROCKET is gone and that\nthey release some of our scientist, we\lcan focus on exploration!\pBLAINE for example is looking into the\nSEAFOAM CAVE, I've heard.\lBROCK is helping us finding fossils in\nMT. MOON.\pAnd I guess our CHAMPION was around\nCERULEAN CAVE at some point.$"

CinnabarInside_Text_Gentleman_Text_0:
	.string "BLAINE and I are friends. I used to\nfight in the GYM alongside him.\lA few months ago a three kids blasted\lthrough the GYM and kick our butts.\pI've decided to retire then.$"

CinnabarInside_Text_OldLady_Text_0:
	.string "I don't know if it's because I'm\ngetting older, but I'm shaking more and\lmore.\lIt's like the ground was about to\lburst!\pStrange isn't it?$"
