AquaHideout_UnusedRubyMap3_MapScripts::
	.byte 0


CeladonCondominium2_Text_DevOffice::
	msgbox CeladonCondominium2_Text_DevOffice_Text_0, MSGBOX_SIGN
	end


CeladonCondominium2_Text_MeetingRoom::
	msgbox CeladonCondominium2_Text_MeetingRoom_Text_0, MSGBOX_SIGN
	end


CeladonCondominium2_Text_Appartment1::
	msgbox CeladonCondominium2_Text_Appartment1_Text_0, MSGBOX_SIGN
	end


CeladonCondominium2_Text_Appartment2::
	msgbox CeladonCondominium2_Text_Appartment2_Text_0, MSGBOX_SIGN
	end


CeladonCondominium2_Text_DevOffice_Text_0:
	.string "Development Room -\nCurrently for rent$"

CeladonCondominium2_Text_MeetingRoom_Text_0:
	.string "Meeting Room$"

CeladonCondominium2_Text_Appartment1_Text_0:
	.string "Appartement 101$"

CeladonCondominium2_Text_Appartment2_Text_0:
	.string "Appartement 201$"
