Route104_Houses_MapScripts::
	.byte 0


Route104_Houses_Text_OldWoman::
	msgbox Route104_Houses_Text_OldWoman_Text_0, MSGBOX_NPC
	end


Route104_Houses_Text_Pokemaniac::
	msgbox Route104_Houses_Text_Pokemaniac_Text_0, MSGBOX_NPC
	end


Route104_Houses_Text_OldWoman_Text_0:
	.string "Hello, you wanna cross the\nPetalburgWoods?\lI think there are rare POKéMON inside.\lLike a TREECKO I think.\lMy memory is fading...$"

Route104_Houses_Text_Pokemaniac_Text_0:
	.string "I wish I had a rare POKéMON...\n{PLAYER}: Why not crawling in the\lgrasses?$"
