PalletTownInside_MapScripts::
	.byte 0


PalletTownInside_Text_Mom::
	lock
	faceplayer
	msgbox PalletTownInside_Text_Mom_Text_0
	release
	end


PalletTownInside_Text_Daisy::
	lock
	faceplayer
	msgbox PalletTownInside_Text_Daisy_Text_0
	release
	end


PalletTownInside_Text_LeafGrandma::
	lock
	faceplayer
	msgbox PalletTownInside_Text_LeafGrandma_Text_0
	release
	end


PalletTownInside_Text_Mom_Text_0:
	.string "Hi !\n"
	.string "RED's been away for a few months. I\l"
	.string "heard he beat BLUE in the POKéMON\l"
	.string "LEAGUE. I think he is seeking for some\l"
	.string "powerful POKéMON.$"

PalletTownInside_Text_Daisy_Text_0:
	.string "DAISY : HI ! My kid brother is weaping\n"
	.string "somewhere. I don't think he got\l"
	.string "throught his DEFEA against RED.$"

PalletTownInside_Text_LeafGrandma_Text_0:
	.string "My grand daughter must be outside. I\n"
	.string "heard she is helping DAISY mapping all\l"
	.string "the REGIONS. She told me she would\l"
	.string "move in JOHTO. But I don't know where.$"
