UnionCave_MapScripts::
	.byte 0


UnionCave_Text_Hiker1::
	trainerbattle_single TRAINER_LAO_3, UnionCave_Text_Hiker1_Text_0, UnionCave_Text_Hiker1_Text_1
	msgbox UnionCave_Text_Hiker1_Text_2, MSGBOX_NPC
	end


UnionCave_Text_Firebreather::
	trainerbattle_single TRAINER_LAO_4, UnionCave_Text_Firebreather_Text_0, UnionCave_Text_Firebreather_Text_1
	msgbox UnionCave_Text_Firebreather_Text_2, MSGBOX_NPC
	end


UnionCave_Text_Hiker2::
	trainerbattle_single TRAINER_CYNDY_2, UnionCave_Text_Hiker2_Text_0, UnionCave_Text_Hiker2_Text_1
	msgbox UnionCave_Text_Hiker2_Text_2, MSGBOX_NPC
	end


UnionCave_Text_Camper::
	trainerbattle_single TRAINER_CYNDY_3, UnionCave_Text_Camper_Text_0, UnionCave_Text_Camper_Text_1
	msgbox UnionCave_Text_Camper_Text_2, MSGBOX_NPC
	end


UnionCave_Text_Pokemaniac::
	trainerbattle_single TRAINER_CYNDY_4, UnionCave_Text_Pokemaniac_Text_0, UnionCave_Text_Pokemaniac_Text_1
	msgbox UnionCave_Text_Pokemaniac_Text_2, MSGBOX_NPC
	end


UnionCave_Text_Hiker1_Text_0:
	.string "Wanna see some bulky POKéMON?$"

UnionCave_Text_Hiker1_Text_1:
	.string "Oh! Your POKéMON as strong as steel!$"

UnionCave_Text_Hiker1_Text_2:
	.string "All right, then!\nI've decided.\lI'm not leaving until my POKéMON get\ltougher!$"

UnionCave_Text_Firebreather_Text_0:
	.string "My POKéMON help me see in the dark.\nWanna see them?$"

UnionCave_Text_Firebreather_Text_1:
	.string "How will I see in the dark now?!$"

UnionCave_Text_Firebreather_Text_2:
	.string "Sometimes you can hear strange roars\nfrom deep in the cave.$"

UnionCave_Text_Hiker2_Text_0:
	.string "I'll go out to investigate old secrets\nand legends.$"

UnionCave_Text_Hiker2_Text_1:
	.string "What is the secret of you power?$"

UnionCave_Text_Hiker2_Text_2:
	.string "The Ruins are hiding something...\nI just know it!$"

UnionCave_Text_Camper_Text_0:
	.string "I don't think that's a good place to\ncamp here.$"

UnionCave_Text_Camper_Text_1:
	.string "Oh wow!$"

UnionCave_Text_Camper_Text_2:
	.string "I think there is a RARE POKéMON\nsomewhere here.$"

UnionCave_Text_Pokemaniac_Text_0:
	.string "Who's there?\nLeave me and my POKéMON alone!$"

UnionCave_Text_Pokemaniac_Text_1:
	.string "Go...\nGo away!$"

UnionCave_Text_Pokemaniac_Text_2:
	.string "Just me and my POKéMON. I'm delirious\nwith joy.$"
