FishingClub_MapScripts::
	.byte 0


TinTowerGate_Text_Sage::
	msgbox TinTowerGate_Text_Sage_Text_0, MSGBOX_NPC
	end


TinTowerGate_Text_OldMan::
	msgbox TinTowerGate_Text_OldMan_Text_0, MSGBOX_NPC
	end


TinTowerGate_Text_Kimono::
	msgbox TinTowerGate_Text_Kimono_Text_0, MSGBOX_NPC
	end


TinTowerGate_Text_Sage_Text_0:
	.string "The way to the TIN TOWER is closed,\nexcept for a TRAINER with a pure heart.$"

TinTowerGate_Text_OldMan_Text_0:
	.string "Two towers…\nTwo POKéMON…\pBut when one burned down, both POKéMON\lflew away, never to return.$"

TinTowerGate_Text_Kimono_Text_0:
	.string "The TIN TOWER ahead is a nine-tier\ntower of divine beauty.\pIt soothes the soul of all who see it.$"
