Route29_MapScripts::
	.byte 0


Route29_Text_TeachyTVGuy::
	lock
	faceplayer
	msgbox Route29_Text_TeachyTVGuy_Text_0
	release
	end


Route29_Text_Youngster::
	lock
	faceplayer
	msgbox Route29_Text_Youngster_Text_0
	release
	end


Route29_Text_BugCatcher::
	lock
	faceplayer
	msgbox Route29_Text_BugCatcher_Text_0
	release
	end


Route29_Text_Lass::
	lock
	faceplayer
	msgbox Route29_Text_Lass_Text_0
	release
	end


Route29_Text_SignCherrygrove::
	lock
	faceplayer
	msgbox Route29_Text_SignCherrygrove_Text_0
	release
	end


Route29_Text_TeachyTVGuy_Text_0:
	.string "Hey young TRAINER ! You don't know me ?\n"
	.string "No ? But I'm the guy on the TV ! I'm\l"
	.string "teaching every basics to new TRAINERS.\l"
	.string "What you are already a CHAMPION ?! Well\l"
	.string "sorry to disturb you then...$"

Route29_Text_Youngster_Text_0:
	.string "Yo. How are your POKéMON ? If they're\n"
	.string "weak and not ready for battle, keep\l"
	.string "out of the grass.$"

Route29_Text_BugCatcher_Text_0:
	.string "I'm waiting for POKéMON that appear\n"
	.string "only at night.$"

Route29_Text_Lass_Text_0:
	.string "See those ledges ? It's scary to jump\n"
	.string "off them. But you can go to NEW BARK\l"
	.string "without walking through the grass.$"

Route29_Text_SignCherrygrove_Text_0:
	.string "ROUTE 29\p"
	.string "CHERRYGROVE CITY - NEW BARK TOWN$"
