FuschiaCity_MapScripts::
	.byte 0


Fuschia_Text_Oldman::
	lock
	faceplayer
	msgbox Fuschia_Text_Oldman_Text_0
	release
	end


Fuschia_Text_Kurt::
	lock
	faceplayer
	msgbox Fuschia_Text_Kurt_Text_0
	release
	end


Fuschia_Text_Youngster::
	lock
	faceplayer
	msgbox Fuschia_Text_Youngster_Text_0
	release
	end


Fuschia_Text_Bugcatcher::
	lock
	faceplayer
	msgbox Fuschia_Text_Bugcatcher_Text_0
	release
	end


Fuschia_Sign_Lapras::
	lock
	faceplayer
	msgbox Fuschia_Sign_Lapras_Text_0
	showmonpic SPECIES_LAPRAS, 10, 3
	waitbuttonpress
	hidemonpic
	release
	end


Fuschia_Sign_Kabuto::
	lock
	faceplayer
	msgbox Fuschia_Sign_Kabuto_Text_0
	showmonpic SPECIES_KABUTO, 10, 3
	waitbuttonpress
	hidemonpic
	release
	end


Fuschia_Sign_Kangaskhan::
	lock
	faceplayer
	msgbox Fuschia_Sign_Kangaskhan_Text_0
	showmonpic SPECIES_KANGASKHAN, 10, 3
	waitbuttonpress
	hidemonpic
	release
	end


Fuschia_Sign_Voltorb::
	lock
	faceplayer
	msgbox Fuschia_Sign_Voltorb_Text_0
	showmonpic SPECIES_VOLTORB, 10, 3
	waitbuttonpress
	hidemonpic
	release
	end


Fuschia_Sign_Chansey::
	lock
	faceplayer
	msgbox Fuschia_Sign_Chansey_Text_0
	showmonpic SPECIES_CHANSEY, 10, 3
	waitbuttonpress
	hidemonpic
	release
	end


Fuschia_Sign_Slowpoke::
	lock
	faceplayer
	msgbox Fuschia_Sign_Slowpoke_Text_0
	showmonpic SPECIES_SLOWPOKE, 10, 3
	waitbuttonpress
	hidemonpic
	release
	end


Fuschia_Sign_FuchsiaSign::
	lock
	faceplayer
	msgbox Fuschia_Sign_FuchsiaSign_Text_0
	release
	end


Fuschia_Sign_SafariZone::
	lock
	faceplayer
	msgbox Fuschia_Sign_SafariZone_Text_0
	release
	end


Fuschia_Text_Camper::
	lock
	faceplayer
	msgbox Fuschia_Text_Camper_Text_0
	release
	end


Fuschia_Sign_WardenHome::
	lock
	faceplayer
	msgbox Fuschia_Sign_WardenHome_Text_0
	release
	end


Fuschia_Sign_SafariGate::
	lock
	faceplayer
	msgbox Fuschia_Sign_SafariGate_Text_0
	release
	end


Fuschia_Text_Cooltrainer::
	lock
	faceplayer
	msgbox Fuschia_Text_Cooltrainer_Text_0
	release
	end


Fuschia_Text_Man::
	lock
	faceplayer
	msgbox Fuschia_Text_Man_Text_0
	release
	end


Fuschia_Text_Lass::
	lock
	faceplayer
	msgbox Fuschia_Text_Lass_Text_0
	release
	end


Fuschia_Sign_Gym::
	lock
	faceplayer
	msgbox Fuschia_Sign_Gym_Text_0
	release
	end


Fuschia_Text_Oldman_Text_0:
	.string "SAFARI ZONE has a zoo in front of the\n"
	.string "entrance. Out back is the SAFARI GAME\l"
	.string "for catching POKéMON.$"

Fuschia_Text_Kurt_Text_0:
	.string "KURT: Where's SHURA ? I said I'd meet\n"
	.string "her here.$"

Fuschia_Text_Youngster_Text_0:
	.string "That item ball in there is really a\n"
	.string "POKéMON.$"

Fuschia_Text_Bugcatcher_Text_0:
	.string "Did you try the SAFARI GAME? Some\n"
	.string "POKéMON can only be caught there.$"

Fuschia_Sign_Lapras_Text_0:
	.string "Name: LAPRAS\n"
	.string "A.K.A the king of the seas.$"

Fuschia_Sign_Kabuto_Text_0:
	.string "Name: KABUTO\n"
	.string "A POKéMON that was resurrected from a\l"
	.string "fossil.$"

Fuschia_Sign_Kangaskhan_Text_0:
	.string "Name: KANGASKHAN\n"
	.string "A maternal POKéMON that raises its\l"
	.string "young in a pouch on its belly.$"

Fuschia_Sign_Voltorb_Text_0:
	.string "Name: VOLTORB\n"
	.string "The very image of a POKéBALL.$"

Fuschia_Sign_Chansey_Text_0:
	.string "Name: CHANSEY\n"
	.string "Catching one is all up to chance.$"

Fuschia_Sign_Slowpoke_Text_0:
	.string "Name: SLOWPOKE\n"
	.string "Friendly and very slow moving.$"

Fuschia_Sign_FuchsiaSign_Text_0:
	.string "FUCHSIA CITY\n"
	.string "Behold! It's passion pink!$"

Fuschia_Sign_SafariZone_Text_0:
	.string "POKéMON Paradise\n"
	.string "Safari Zone$"

Fuschia_Text_Camper_Text_0:
	.string "It's the residential area of FUCHSIA\n"
	.string "CITY. I heard tourists are hosted here.$"

Fuschia_Sign_WardenHome_Text_0:
	.string "Safari Zone\n"
	.string "Warden's home$"

Fuschia_Sign_SafariGate_Text_0:
	.string "Safari Game\n"
	.string "POKéMON-u-Catch !$"

Fuschia_Text_Cooltrainer_Text_0:
	.string "I wonder if there are rare POKéMON in\n"
	.string "the SAFARI ZONE.\l"
	.string "Yes ?\p"
	.string "Well I'm going there right now !$"

Fuschia_Text_Man_Text_0:
	.string "KOGA our GYM LEADER left for his\n"
	.string "ancestors' home village. It's in JOHTO I\l"
	.string "think !$"

Fuschia_Text_Lass_Text_0:
	.string "I wish I could catch a CHANSEY... SIGH !$"

Fuschia_Sign_Gym_Text_0:
	.string "FUCHSIA CITY\n"
	.string "POKéMON GYM\l"
	.string "LEADER: KOGA\p"
	.string "The poisonous ninja master !$"
