CeruleanBikeShop_MapScripts::
	.byte 0


CeruleanBikeShop_Text_Woman::
	msgbox CeruleanBikeShop_Text_Woman_Text_0, MSGBOX_NPC
	end


CeruleanBikeShop_Text_Youngster::
	msgbox CeruleanBikeShop_Text_Youngster_Text_0, MSGBOX_NPC
	end


CeruleanBikeShop_Text_Clerk::
	msgbox CeruleanBikeShop_Text_Clerk_Text_0, MSGBOX_NPC
	end


CeruleanBikeShop_Text_Bike::
	msgbox CeruleanBikeShop_Text_Bike_Text_0, MSGBOX_SIGN
	end


CeruleanBikeShop_Text_Woman_Text_0:
	.string "A plain city bike is good enough\n"
	.string "for me.\p"
	.string "After all, you can't put a shopping\n"
	.string "basket on a mountain bike.$"

CeruleanBikeShop_Text_Youngster_Text_0:
	.string "These bikes are cool, but they're\n"
	.string "way expensive!$"

CeruleanBikeShop_Text_Clerk_Text_0:
	.string "Oh hey!\nLooks like you have a pretty neat BIKE!\lMay I see it?\l...........\lDamn!\l...........\lAnd you can do even switch with another\lkind of BIKE?!\lI need to expand my market, otherwise\lI'm broke!$"

CeruleanBikeShop_Text_Bike_Text_0:
	.string "A shiny new BICYCLE!$"
