EcruteakToRoute38_MapScripts::
	.byte 0


EcruteakToRoute38_Text_Police::
	msgbox EcruteakToRoute38_Text_Police_Text_0, MSGBOX_NPC
	end


EcruteakToRoute38_Text_OldWoman::
	msgbox EcruteakToRoute38_Text_OldWoman_Text_0, MSGBOX_NPC
	end


EcruteakToRoute38_Text_Police_Text_0:
	.string "This ROUTE leads to OLIVINE and also\nthe MOOMOO FARM!\lBut I think you already know that.$"

EcruteakToRoute38_Text_OldWoman_Text_0:
	.string "My sister is planting crops in ROUTE\n38.\lI can't help her, my back is too\lpainful…$"
