AquaHideout_UnusedRubyMap2_MapScripts::
	.byte 0


ViridianForest_Text_Youngster::
	trainerbattle_single TRAINER_FERNANDO_3, ViridianForest_Text_Youngster_Text_0, ViridianForest_Text_Youngster_Text_1
	msgbox ViridianForest_Text_Youngster_Text_2, MSGBOX_AUTOCLOSE
	end


ViridianForest_Text_Lass::
	trainerbattle_single TRAINER_FERNANDO_4, ViridianForest_Text_Lass_Text_0, ViridianForest_Text_Lass_Text_1
	msgbox ViridianForest_Text_Lass_Text_2, MSGBOX_AUTOCLOSE
	end


ViridianForest_Text_BugCatcher1::
	trainerbattle_single TRAINER_DALTON_2, ViridianForest_Text_BugCatcher1_Text_0, ViridianForest_Text_BugCatcher1_Text_1
	msgbox ViridianForest_Text_BugCatcher1_Text_2, MSGBOX_AUTOCLOSE
	end


ViridianForest_Text_BugCatcher2::
	trainerbattle_single TRAINER_DALTON_3, ViridianForest_Text_BugCatcher2_Text_0, ViridianForest_Text_BugCatcher2_Text_1
	msgbox ViridianForest_Text_BugCatcher2_Text_2, MSGBOX_AUTOCLOSE
	end


ViridianForest_Text_Youngster_Text_0:
	.string "Hey you came for some battle ?$"

ViridianForest_Text_Youngster_Text_1:
	.string "And another defeat...$"

ViridianForest_Text_Youngster_Text_2:
	.string "All my friends are gone now. There are\n"
	.string "just a few.$"

ViridianForest_Text_Lass_Text_0:
	.string "I found a PIKACHU, wanna see it ?$"

ViridianForest_Text_Lass_Text_1:
	.string "Oh rude !$"

ViridianForest_Text_Lass_Text_2:
	.string "I heard some places have ELECTRIK\n"
	.string "POKéMON only.$"

ViridianForest_Text_BugCatcher1_Text_0:
	.string "Hey there are a lots of BUGS here$"

ViridianForest_Text_BugCatcher1_Text_1:
	.string "Watch where you put your step !$"

ViridianForest_Text_BugCatcher1_Text_2:
	.string "Ssh ! You'll scare the bugs away !$"

ViridianForest_Text_BugCatcher2_Text_0:
	.string "Haha I'm the last one here !\nLet's fight !$"

ViridianForest_Text_BugCatcher2_Text_1:
	.string "I'm beaten again !$"

ViridianForest_Text_BugCatcher2_Text_2:
	.string "Sometimes, you can find stuff on the\n"
	.string "ground ! I'm looking for the stuff I\l"
	.string "dropped !$"
