NationalPark_MapScripts::
	.byte 0


NationalPark_Text_Beauty::
	msgbox NationalPark_Text_Beauty_Text_0, MSGBOX_NPC
	end


NationalPark_Text_Woman::
	msgbox NationalPark_Text_Woman_Text_0, MSGBOX_NPC
	end


NationalPark_Text_Picnicker::
	msgbox NationalPark_Text_Picnicker_Text_0, MSGBOX_NPC
	end


NationalPark_Text_Youngster::
	msgbox NationalPark_Text_Youngster_Text_0, MSGBOX_NPC
	end


NationalPark_Text_Bugcatcher::
	msgbox NationalPark_Text_Bugcatcher_Text_0, MSGBOX_NPC
	end


NationalPark_Text_GbaBoy1::
	msgbox NationalPark_Text_GbaBoy1_Text_0, MSGBOX_NPC
	end


NationalPark_Text_GbaBoy2::
	msgbox NationalPark_Text_GbaBoy2_Text_0, MSGBOX_NPC
	end


NationalPark_Text_Lass::
	msgbox NationalPark_Text_Lass_Text_0, MSGBOX_NPC
	end


NationalPark_Text_Meowth::
	playmoncry SPECIES_MEOWTH, CRY_MODE_NORMAL
	msgbox NationalPark_Text_Meowth_Text_0, MSGBOX_NPC
	end


NationalPark_Text_Beauty_Text_0:
	.string "Huh? What?\nOh no I'm just trying to write a letter\lto my mom.\lYou should do the same.$"

NationalPark_Text_Woman_Text_0:
	.string "My friend keeps a MARILL! I find them\nvery endearing.\lOh, I wish for a MARILL of my own…$"

NationalPark_Text_Picnicker_Text_0:
	.string "I need to find a SCYTHER. I'll be\ninvincible!$"

NationalPark_Text_Youngster_Text_0:
	.string "I heard a SNORLAX was roaming around.\nBut that's crazy right?$"

NationalPark_Text_Bugcatcher_Text_0:
	.string "I'm the real deal when it's about\ncatching BUGS!$"

NationalPark_Text_GbaBoy1_Text_0:
	.string "I'm playing against a friend.\nIt's wireless. It's crazy how\ltechnology evolved!$"

NationalPark_Text_GbaBoy2_Text_0:
	.string "I always come to the PARK but I don't\nwalk in the GRASS.\lImagine what would happens to my\lgameboy is I'm getting attacked.$"

NationalPark_Text_Lass_Text_0:
	.string "I want to become a teacher, but I have\nto teach first my MEOWTH to obey…$"

NationalPark_Text_Meowth_Text_0:
	.string "MEOWTH: Meow!$"
