NewBarkInside_MapScripts::
	.byte 0


NewBarkTown_Text_GoldMom::
	lock
	faceplayer
	msgbox NewBarkTown_Text_GoldMom_Text_0
	release
	end


NewBarkTown_Text_ElmWife::
	lock
	faceplayer
	msgbox NewBarkTown_Text_ElmWife_Text_0
	release
	end


NewBarkTown_Text_Girl::
	lock
	faceplayer
	msgbox NewBarkTown_Text_Girl_Text_0
	release
	end


NewBarkTown_Text_GoldMom_Text_0:
	.string "Hello you, you seem to be a little older\n"
	.string "than my son. He is studying POKéMON\l"
	.string "with the PROF. ELM. He is so dedicated\l"
	.string "to that. He is in our garden currently.\l"
	.string "Focus on strategy or something. Kids...\l"
	.string "Haha !$"

NewBarkTown_Text_ElmWife_Text_0:
	.string "Hello there ! My husband's always so\n"
	.string "busy. I hope he's OK. When he's caught\l"
	.string "up in his POKéMON research, he even\l"
	.string "forget to eat. Sometime he even go\l"
	.string "come home...$"

NewBarkTown_Text_Girl_Text_0:
	.string "Professor Elm field of research is\n"
	.string "EVOLUTION. He taught us a lot about\l"
	.string "EVOLUTION !$"
