Deford_Multiple_Houses_MapScripts::
	.byte 0


Dewford_MultipleHouse_Text_WingullGirl::
	lock
	faceplayer
	msgbox Dewford_MultipleHouse_Text_WingullGirl_Text_0
	release
	end


Dewford_MultipleHouse_Text_Camper::
	lock
	faceplayer
	msgbox Dewford_MultipleHouse_Text_Camper_Text_0
	release
	end


Dewford_MultipleHouse_Text_Fisherman::
	lock
	faceplayer
	msgbox Dewford_MultipleHouse_Text_Fisherman_Text_0
	release
	end


Dewford_MultipleHouse_Text_Man::
	lock
	faceplayer
	msgbox Dewford_MultipleHouse_Text_Man_Text_0
	release
	end


Dewford_MultipleHouse_Text_OldMan::
	lock
	faceplayer
	msgbox Dewford_MultipleHouse_Text_OldMan_Text_0
	release
	end


Dewford_MultipleHouse_Text_OldWoman::
	lock
	faceplayer
	msgbox Dewford_MultipleHouse_Text_OldWoman_Text_0
	release
	end


Dewford_MultipleHouse_Text_WarriorF::
	lock
	faceplayer
	msgbox Dewford_MultipleHouse_Text_WarriorF_Text_0
	release
	end


Dewford_MultipleHouse_Text_Ninja::
	lock
	faceplayer
	msgbox Dewford_MultipleHouse_Text_Ninja_Text_0
	release
	end


Dewford_MultipleHouse_Text_Artist::
	lock
	faceplayer
	msgbox Dewford_MultipleHouse_Text_Artist_Text_0
	release
	end


Dewford_MultipleHouse_Text_Boy::
	lock
	faceplayer
	msgbox Dewford_MultipleHouse_Text_Boy_Text_0
	release
	end


Dewford_MultipleHouse_Text_LittleBoy::
	lock
	faceplayer
	msgbox Dewford_MultipleHouse_Text_LittleBoy_Text_0
	release
	end


Dewford_MultipleHouse_Text_LittleGirl::
	lock
	faceplayer
	msgbox Dewford_MultipleHouse_Text_LittleGirl_Text_0
	release
	end


Dewford_MultipleHouse_Text_WingullGirl_Text_0:
	.string "The WINGULLS invades my house!\n"
	.string "I'm too afraid to move and\l"
	.string "myparents are outside...\l"
	.string "{PLAYER}: I'm sorry for you. Too\l"
	.string "bad I don't have a POKéMON to\l"
	.string "defeat them right?$"

Dewford_MultipleHouse_Text_Camper_Text_0:
	.string "You know DEWFORD is very famous\n"
	.string "for the fighting GYM?\l"
	.string "There is a training ground where\l"
	.string "everybody trained westward!\l"
	.string "Why don't you check that place?$"

Dewford_MultipleHouse_Text_Fisherman_Text_0:
	.string "My brother spent his time looking\n"
	.string "for the best place to camp.\l"
	.string "He found that the training grounds\l"
	.string "are a good place, so we move in\l"
	.string "DEWFORD.$"

Dewford_MultipleHouse_Text_Man_Text_0:
	.string "I'm afraid the kids outside are\n"
	.string "plotting something nasty!\l"
	.string "Wait! Who told you to come in my\l"
	.string "house?!$"

Dewford_MultipleHouse_Text_OldMan_Text_0:
	.string "My sister came from LAVARIDGE to\n"
	.string "see us.\l"
	.string "But she and my wife turned me into\l"
	.string "a dishwasher!\l"
	.string "Back in my day...\l"
	.string "Grumbl..!$"

Dewford_MultipleHouse_Text_OldWoman_Text_0:
	.string "My husband asked me to prepare a\n"
	.string "dish. I said ok but he had to wash\l"
	.string "after that.\l"
	.string "Now he is pissed.\l"
	.string "What a kid!$"

Dewford_MultipleHouse_Text_WarriorF_Text_0:
	.string "I came to see my brother and his\n"
	.string "wife, but I'm in the middle of a\l"
	.string "fight.\l"
	.string "I just wanted to show him the EGG\l"
	.string "I got in LAVARIDGE...\l"
	.string "But hey! With all that wrath, the\l"
	.string "EGG is gonna natch soon!$"

Dewford_MultipleHouse_Text_Ninja_Text_0:
	.string "Sorry, but here is my secret\n"
	.string "place!\l"
	.string "I can't let you in pal!$"

Dewford_MultipleHouse_Text_Artist_Text_0:
	.string "I'm supposed to watch this kid but\n"
	.string "I think he locked a POKéMON behind\l"
	.string "the door, but I'm too scare to do\l"
	.string "something! Look at his face!!$"

Dewford_MultipleHouse_Text_Boy_Text_0:
	.string "My parents went to the sea to\n"
	.string "catch some fishes.\l"
	.string "But they aren't back...$"

Dewford_MultipleHouse_Text_LittleBoy_Text_0:
	.string "Yeah! Our parents aren't home!\n"
	.string "I'm gonna be on the beach everyday\l"
	.string "eating ice cream!$"

Dewford_MultipleHouse_Text_LittleGirl_Text_0:
	.string "I'm scared because our parents\n"
	.string "aren't back home yet. I hope\l"
	.string "nothing happened to them...$"
