CaveOfOrigin_UnusedRubySapphireMap2_MapScripts::
	.byte 0


OlivinePub_Text_SwimmerF::
	msgbox OlivinePub_Text_SwimmerF_Text_0, MSGBOX_NPC
	end


OlivinePub_Text_Sailor::
	msgbox OlivinePub_Text_Sailor_Text_0, MSGBOX_NPC
	end


OlivineInside_Text_Fisherman::
	msgbox OlivineInside_Text_Fisherman_Text_0, MSGBOX_NPC
	end


OlivineInside_Text_Youngster::
	msgbox OlivineInside_Text_Youngster_Text_0, MSGBOX_NPC
	end


OlivineInside_Text_Man::
	msgbox OlivineInside_Text_Man_Text_0, MSGBOX_NPC
	end


OlivineInside_Text_OldWoman::
	msgbox OlivineInside_Text_OldWoman_Text_0, MSGBOX_NPC
	end


OlivineInside_Text_OldMan::
	msgbox OlivineInside_Text_OldMan_Text_0, MSGBOX_NPC
	end


OlivineInside_Text_Gentleman::
	msgbox OlivineInside_Text_Gentleman_Text_0, MSGBOX_NPC
	end


OlivineCafe_Text_Cook::
	msgbox OlivineCafe_Text_Cook_Text_0, MSGBOX_NPC
	end


OlivinePub_Text_SwimmerF_Text_0:
	.string "There is absolutely no way this place\nis so good!\lIt looks garbage from the outside, but\lthe menu is the best!$"

OlivinePub_Text_Sailor_Text_0:
	.string "OLIVINE'S CAFÉ is full of fresh fishes\nand good old steak!$"

OlivineInside_Text_Fisherman_Text_0:
	.string "The sea is sweet!\nSunsets on the sea are marvelous!\lAnd that bring a lot of fishes!$"

OlivineInside_Text_Youngster_Text_0:
	.string "Three orbs!\nOne light!\lExtinguish them all, and bring forth\lthe night!\lOh! It's a song I sing a lot to my\lsister.$"

OlivineInside_Text_Man_Text_0:
	.string "A POKéMON with darkness in its heart is\na scary thing to think about.\lCould that happen?$"

OlivineInside_Text_OldWoman_Text_0:
	.string "Oh {PLAYER}! You are back from HOENN\nalready?\lJASMINE is not around. I think she is\ltraining somewhere.$"

OlivineInside_Text_OldMan_Text_0:
	.string "Wanna go to the four ISLANDS?\nI heard that during the night you can\lhear some voices.\lIt's said to be the voices of young\lbrats that died there.\lBrrrr!$"

OlivineInside_Text_Gentleman_Text_0:
	.string "Hey {PLAYER}!\nSince you are a TRAINER now, you should\lknow about the legendary POKéMON living\lin the WHIRL ISLANDS?\lIt is said that a mythical creature\llive in the sea above the caves.\lYou can hear some song around the cave.\lMy brother thinks it's some ghost.\lBut he is a supersticious jerk!\lMy theory is that a POKéMON lives\lthere.$"

OlivineCafe_Text_Cook_Text_0:
	.string "I'm sorry but I won't cook for you\nPOKéMON.\lThat's not how we do things here.$"
