LakeofRageInside_MapScripts::
	.byte 0


LakeofRage_Text_FishingGuru::
	lock
	faceplayer
	msgbox LakeofRage_Text_FishingGuru_Text_0
	release
	end


LakeofRage_Text_Pokemaniac::
	lock
	faceplayer
	msgbox LakeofRage_Text_Pokemaniac_Text_0
	release
	end


LakeofRage_Text_FishingGuru_Text_0:
	.string "Hello, I'm a simple fishing guy. And I\nenjoy my life here in the LAKE of\lRAGE.\lI want to see the biggest\lMAGIKARP in the world !\lDo you have that?\lNo?\lDisappointing...$"

LakeofRage_Text_Pokemaniac_Text_0:
	.string "Hello...\nWhat do you want ?...\lI'm watching TV...\lIt's about a kid you woke up late and\lhas a yellow mouse...\lOh yeah, it's POKéMON!$"
