ViridianCity_MapScripts::
	.byte 0


ViridianCity_Text_Youngster::
	lock
	faceplayer
	msgbox ViridianCity_Text_Youngster_Text_0
	release
	end


ViridianCity_Text_Rattata::
	lock
	faceplayer
	playmoncry SPECIES_RATTATA, CRY_MODE_NORMAL
	msgbox ViridianCity_Text_Rattata_Text_0
	release
	end


ViridianCity_Text_Fatman::
	lock
	faceplayer
	msgbox ViridianCity_Text_Fatman_Text_0
	release
	end


ViridianCity_Text_Teacher::
	lock
	faceplayer
	msgbox ViridianCity_Text_Teacher_Text_0
	release
	end


ViridianCity_Text_Man::
	lock
	faceplayer
	msgbox ViridianCity_Text_Man_Text_0
	release
	end


ViridianCity_Text_Oldman::
	lock
	faceplayer
	msgbox ViridianCity_Text_Oldman_Text_0
	release
	end


ViridianCity_Text_Worker::
	lock
	faceplayer
	msgbox ViridianCity_Text_Worker_Text_0
	release
	end


ViridianCity_Text_CitySign::
	lock
	msgbox ViridianCity_Text_CitySign_Text_0
	release
	end


ViridianCity_Text_ToIndigoSign::
	lock
	msgbox ViridianCity_Text_ToIndigoSign_Text_0
	release
	end


ViridianCity_Text_SchoolSign::
	lock
	msgbox ViridianCity_Text_SchoolSign_Text_0
	release
	end


ViridianCity_Text_GymSign::
	lock
	msgbox ViridianCity_Text_GymSign_Text_0
	release
	end


ViridianCity_Text_Camper::
	lock
	msgbox ViridianCity_Text_Camper_Text_0
	release
	end


ViridianCity_Text_Picnicker::
	lock
	msgbox ViridianCity_Text_Picnicker_Text_0
	release
	end


ViridianCity_Text_Youngster_Text_0:
	.string "This is my friend RATTATA ! I found him\n"
	.string "in my attic. I fed him and now he follow\l"
	.string "me everywere ! That 's a real pal !$"

ViridianCity_Text_Rattata_Text_0:
	.string "Rattti !\n"
	.string "{PLAYER}: I can see in it's eyes that\l"
	.string "this RATTATA is only here for free\l"
	.string "food.$"

ViridianCity_Text_Fatman_Text_0:
	.string "I just want to sleep, but my dream have\n"
	.string "been eaten ! I'm so pissed right now !$"

ViridianCity_Text_Teacher_Text_0:
	.string "Here is the VIRIDIAN SCHOOL ! You are\n"
	.string "welcome young... Oh ! so much BADGES !\l"
	.string "Sorry mylord.$"

ViridianCity_Text_Man_Text_0:
	.string "Those POKéBALLS at your waist ! You\n"
	.string "have POKéMON ! It's great that you can\l"
	.string "carry and use POKéMON anytime,\l"
	.string "anywhere ! {PLAYER}: Even if they\l"
	.string "have the power to destroy the world ?$"

ViridianCity_Text_Oldman_Text_0:
	.string "I have such a hangover... You are in a\n"
	.string "hurry right ? Well time is money...$"

ViridianCity_Text_Worker_Text_0:
	.string "Well, since the previous GYM LEADER\n"
	.string "vanished, this GYM is closed...$"

ViridianCity_Text_CitySign_Text_0:
	.string "VIRIDIAN CITY\n"
	.string "The Eternally Green Paradise$"

ViridianCity_Text_ToIndigoSign_Text_0:
	.string "Welcome to VIRIDIAN CITY, The gateway\n"
	.string "to INDIGO PLATEAU$"

ViridianCity_Text_SchoolSign_Text_0:
	.string "VIRIDIAN CITY School$"

ViridianCity_Text_GymSign_Text_0:
	.string "VIRIDIAN CITY GYM\n"
	.string "But the rest is paint in black$"

ViridianCity_Text_Camper_Text_0:
	.string "So if GIOVANNI is not the LEADER, we\n"
	.string "still have no LEADER, again !$"

ViridianCity_Text_Picnicker_Text_0:
	.string "I'm so frustrated about having no\n"
	.string "LEADER. I mean, I'm suppose to take the\l"
	.string "VIRIDIAN FOREST to get my first BADGE\l"
	.string "?$"
