PetalburgSchool_MapScripts::
	.byte 0


PetalburgSchool_Text_Teacher::
	msgbox PetalburgSchool_Text_Teacher_Text_0, MSGBOX_NPC
	end


PetalburgSchool_Text_Salaryman::
	msgbox PetalburgSchool_Text_Salaryman_Text_0, MSGBOX_NPC
	end


PetalburgSchool_Text_Girl::
	msgbox PetalburgSchool_Text_Girl_Text_0, MSGBOX_NPC
	end


PetalburgSchool_Text_BugCatcher::
	msgbox PetalburgSchool_Text_BugCatcher_Text_0, MSGBOX_NPC
	end


PetalburgSchool_Text_Blackboard::
	msgbox PetalburgSchool_Text_Blackboard_Text_0, MSGBOX_SIGN
	end


PetalburgSchool_Text_Teacher_Text_0:
	.string "Hello, you have a POKéDEX? So are you a\nrookie or an expert of POKéMON?\lAnyway, feel free to read the\lblackboard if you think you forgot\lsomething.$"

PetalburgSchool_Text_Salaryman_Text_0:
	.string "I got fired from my agency... So now I\nneed to learn the basics of POKéMON if\lI want to travel in the world to find\lanother job.\lI heard they are recruiting in KANTO.$"

PetalburgSchool_Text_Girl_Text_0:
	.string "My current goal is to beat the GYM\nLEADER!\lHe was so mean with Pappy! I'm gonna\lteach him who's the boss.$"

PetalburgSchool_Text_BugCatcher_Text_0:
	.string "The NEST BALL is the best to catch BUG\nPOKéMON!\lBut it's a bit more expensive than the\lregular POKéBALL!\lIt's a big bummer!$"

PetalburgSchool_Text_Blackboard_Text_0:
	.string "{PLAYER}: It's the blackboard....\nHmmmm....\lIt's written that Sunny Day boosts\lFire-type moves.\lIt’s a great combo with Flamethrower!\lI should keep that in mind!$"
