BlackAzaleaInside_MapScripts::
	.byte 0


AzaleaTownMart_Text_Man::
	msgbox AzaleaTownMart_Text_Man_Text_0, MSGBOX_NPC
	end


AzaleaCharcoalKiln_Text_Kid::
	msgbox AzaleaCharcoalKiln_Text_Kid_Text_0, MSGBOX_NPC
	end


AzaleaCharcoalKiln_Text_Master::
	msgbox AzaleaCharcoalKiln_Text_Master_Text_0, MSGBOX_NPC
	end


AzaleaTownMart_Text_Man_Text_0:
	.string "If only KURT could industrialized his\nBALLS crafting…$"

AzaleaCharcoalKiln_Text_Kid_Text_0:
	.string "My master is producing CHARCOAL with\nthe wood from ILEX FOREST.\lHis brother is there with FARFETCH'D to\lcut trees.$"

AzaleaCharcoalKiln_Text_Master_Text_0:
	.string "I let my brother use the ability to cut\nof my FARFETCH'd.\lI know he wont lose my lovely Bird!$"
