Littleroot_Docks_MapScripts::
	.byte 0

LittleRootDocks_Text_Sailor::
	lock
	faceplayer
	msgbox LittleRootDocks_Text_Sailor_Text_0
	release
	end


LittleRootDocks_Text_Sailor2::
	lock
	faceplayer
	msgbox LittleRootDocks_Text_Sailor2_Text_0
	release
	end


LittleRootDocks_Text_Woman::
	lock
	faceplayer
	msgbox LittleRootDocks_Text_Woman_Text_0
	release
	end


LittleRootDocks_Text_Worker::
	lock
	faceplayer
	msgbox LittleRootDocks_Text_Worker_Text_0
	release
	end


LittleRootDocks_Text_Truck::
	lock
	faceplayer
	msgbox LittleRootDocks_Text_Truck_Text_0
	release
	end


LittleRootDocks_Text_Girl::
	lock
	faceplayer
	msgbox LittleRootDocks_Text_Girl_Text_0
	release
	end


LittleRootDocks_Text_Sailor_Text_0:
	.string "No I can't let you in. It is restricted\n"
	.string "to authorized people only.\p"
	.string "What's inside ? Well basically this is\n"
	.string "the commercial docks for all the\l"
	.string "REGION. I'm pretty sure that theTRUCK\l"
	.string "you came from at the beggining of the\l"
	.string "GAME came from here.\p"
	.string "{PLAYER} : What the... ?$"

LittleRootDocks_Text_Sailor2_Text_0:
	.string "I have to move a few things in the\n"
	.string "warehouse, but I don't know where to\l"
	.string "start !$"

LittleRootDocks_Text_Woman_Text_0:
	.string "The guy around is moving all around and\n"
	.string "basically wasting time. I think I should\l"
	.string "call someone to fire him.\n"
	.string "What a useless man...$"

LittleRootDocks_Text_Worker_Text_0:
	.string "There are a few things to do here, but\n"
	.string "honestly that's a lazy job !$"

LittleRootDocks_Text_Truck_Text_0:
	.string "{PLAYER} : Looks like the TRUCK that\n"
	.string "brought me to LITTLEROOT TOWN.$"

LittleRootDocks_Text_Girl_Text_0:
	.string "I love this BEACH just a little south\n"
	.string "from LITTLEROOT TOWN. I come fishing\l"
	.string "everydays !$"
