SaffronFanClub_MapScripts::
	.byte 0


SaffronFanClub_Text_Gentleman::
	msgbox SaffronFanClub_Text_Gentleman_Text_0, MSGBOX_NPC
	end


SaffronFanClub_Text_BlackBelt::
	msgbox SaffronFanClub_Text_BlackBelt_Text_0, MSGBOX_NPC
	end


SaffronFanClub_Text_Youngster::
	msgbox SaffronFanClub_Text_Youngster_Text_0, MSGBOX_NPC
	end


SaffronFanClub_Text_Beauty::
	msgbox SaffronFanClub_Text_Beauty_Text_0, MSGBOX_NPC
	end


SaffronFanClub_Text_Woman::
	msgbox SaffronFanClub_Text_Woman_Text_0, MSGBOX_NPC
	end


SaffronFanClub_Text_LittleGirl::
	msgbox SaffronFanClub_Text_LittleGirl_Text_0, MSGBOX_NPC
	end


SaffronFanClub_Text_Rocker::
	msgbox SaffronFanClub_Text_Rocker_Text_0, MSGBOX_NPC
	end


SaffronFanClub_Text_BattleGirl::
	msgbox SaffronFanClub_Text_BattleGirl_Text_0, MSGBOX_NPC
	end


SaffronFanClub_Text_Gentleman_Text_0:
	.string "Do you know RED?\nI've had the pleasure of watching his\lbattles.\lIt brings back sweet memories of my\lown long-lost youth.\lMay you find success and reach RED's\llevel.$"

SaffronFanClub_Text_BlackBelt_Text_0:
	.string "Hiyah! I respect my MASTER at the\nFIGHTING DOJO.\pI will never become a fan of\nanyone other than my MASTER!\pI will even sneak out of the DOJO\nto spread word of his greatness.\pHiyah!$"

SaffronFanClub_Text_Youngster_Text_0:
	.string "…  …\p…  …\nI'm BROCK's fan!\pEven if I were his only fan,\nI swear it on my rock-hard will,\land on my shorts!\pI'll be his fan to the bitter end!$"

SaffronFanClub_Text_Beauty_Text_0:
	.string "Hmm…\nAnd you are?\pWere you hoping to sign up for\na membership in our FAN CLUB?$"

SaffronFanClub_Text_Woman_Text_0:
	.string "All of us gathered here are fans\nof POKéMON TRAINERS.\pThe way they look in battle…\nThey are the picture of coolness.\pPerhaps you will be talked about\nhere, too, if you keep winning.$"

SaffronFanClub_Text_LittleGirl_Text_0:
	.string "Even if I'm the only one, I won't\nstop being SABRINA's fan.\pMy dream is to be like SABRINA,\ncute, but cool.\pI want to be a psychic girl just\nlike her!$"

SaffronFanClub_Text_Rocker_Text_0:
	.string "I wonder if I can become a cool\nTRAINER one day?$"

SaffronFanClub_Text_BattleGirl_Text_0:
	.string "Recently, LEAF has been on\nfire.\pThe way she battles… It's just \nthe way that I like it!$"
