AlphaRuinsDoors_MapScripts::
	.byte 0


AlphaRuinsDoors_Text_Scientist::
	msgbox AlphaRuinsDoors_Text_Scientist_Text_0, MSGBOX_NPC
	end


AlphaRuinsDoors_Text_Police::
	msgbox AlphaRuinsDoors_Text_Police_Text_0, MSGBOX_NPC
	end


AlphaRuinsDoors_Text_Scientist_Text_0:
	.string "You came to investigate the RUINS with\nus?\lWell, glad to see a future archeologist\lthen!$"

AlphaRuinsDoors_Text_Police_Text_0:
	.string "Here are the RUINS of ALPH.\nThe air is so odd here. It's like we\lare constantly watch...$"
